const TEAMS = {
  brazil: {
    name: "Brazil", flag: "🇧🇷", flagCode: "br", color: "#009c3b", accent: "#ffdf00", textColor: "#fff",
    players: [
      { id: 1,  number: 1,  firstName: "Alisson",    lastName: "Becker",      age: 33, club: "Liverpool",       position: "GK",  isRare: false, rating: 76, tmId: 105470 },
      { id: 2,  number: 2,  firstName: "Ederson",    lastName: "",            age: 32, club: "Fenerbahce",      position: "GK",  isRare: false, rating: 71, tmId: 238223 },
      { id: 3,  number: 3,  firstName: "Weverton",   lastName: "",            age: 38, club: "Grêmio",          position: "GK",  isRare: false, rating: 50, tmId: 68252  },
      { id: 4,  number: 4,  firstName: "Gabriel",    lastName: "Magalhães",   age: 28, club: "Arsenal",         position: "CB",  isRare: true,  rating: 90, tmId: 394074 },
      { id: 5,  number: 5,  firstName: "Bremer",      lastName: "",            age: 29, club: "Juventus",        position: "CB",  isRare: false, rating: 83, tmId: 394015 },
      { id: 6,  number: 6,  firstName: "Marquinhos", lastName: "",            age: 32, club: "PSG",             position: "CB",  isRare: true,  rating: 81, tmId: 181971 },
      { id: 7,  number: 7,  firstName: "Ibañez",     lastName: "",            age: 27, club: "Al-Ahli",         position: "CB",  isRare: false, rating: 76, tmId: 422058 },
      { id: 8,  number: 8,  firstName: "Léo",        lastName: "Pereira",     age: 30, club: "Flamengo",        position: "CB",  isRare: false, rating: 71, tmId: 351291 },
      { id: 9,  number: 9,  firstName: "Danilo",     lastName: "",            age: 34, club: "Flamengo",        position: "CB",  isRare: false, rating: 58, tmId: 125782 },
      { id: 10, number: 10, firstName: "Wesley",     lastName: "",            age: 22, club: "Roma",            position: "RB",  isRare: false, rating: 84, tmId: 0      },
      { id: 11, number: 11, firstName: "Douglas",    lastName: "Santos",      age: 32, club: "Zenit",           position: "LB",  isRare: false, rating: 69, tmId: 222026 },
      { id: 12, number: 12, firstName: "Alex",       lastName: "Sandro",      age: 35, club: "Flamengo",        position: "LB",  isRare: false, rating: 54, tmId: 67393  },
      { id: 13, number: 13, firstName: "Bruno",      lastName: "Guimarães",   age: 28, club: "Newcastle",       position: "CM",  isRare: true,  rating: 90, tmId: 339423 },
      { id: 14, number: 14, firstName: "Casemiro",   lastName: "",            age: 34, club: "Man United",      position: "CDM", isRare: true,  rating: 69, tmId: 114965 },
      { id: 15, number: 15, firstName: "Danilo",     lastName: "Santos",      age: 25, club: "Botafogo",        position: "CM",  isRare: false, rating: 79, tmId: 0      },
      { id: 16, number: 16, firstName: "Fabinho",    lastName: "",            age: 32, club: "Al-Ittihad",      position: "CDM", isRare: false, rating: 74, tmId: 113562 },
      { id: 17, number: 17, firstName: "Lucas",      lastName: "Paquetá",     age: 28, club: "Flamengo",        position: "CAM", isRare: true,  rating: 83, tmId: 339710 },
      { id: 18, number: 18, firstName: "Neymar",     lastName: "",            age: 34, club: "Santos",          position: "CAM", isRare: true,  rating: 71, tmId: 18081  },
      { id: 19, number: 19, firstName: "Vinícius",   lastName: "Jr.",         age: 25, club: "Real Madrid",     position: "LW",  isRare: true,  rating: 96, tmId: 371998 },
      { id: 20, number: 20, firstName: "Raphinha",   lastName: "",            age: 29, club: "Barcelona",       position: "LW",  isRare: true,  rating: 91, tmId: 340950 },
      { id: 21, number: 21, firstName: "Gabriel",    lastName: "Martinelli",  age: 24, club: "Arsenal",         position: "LW",  isRare: true,  rating: 85, tmId: 446143 },
      { id: 22, number: 22, firstName: "Rayan",      lastName: "",            age: 19, club: "Bournemouth",     position: "RW",  isRare: false, rating: 84, tmId: 0      },
      { id: 23, number: 23, firstName: "Luiz",       lastName: "Henrique",    age: 25, club: "Zenit",           position: "RW",  isRare: false, rating: 79, tmId: 0      },
      { id: 24, number: 24, firstName: "Matheus",    lastName: "Cunha",       age: 26, club: "Man United",      position: "ST",  isRare: true,  rating: 89, tmId: 446453 },
      { id: 25, number: 25, firstName: "Igor",       lastName: "Thiago",      age: 24, club: "Brentford",       position: "ST",  isRare: false, rating: 86, tmId: 0      },
      { id: 26, number: 26, firstName: "Endrick",    lastName: "",            age: 19, club: "Lyon",            position: "ST",  isRare: true,  rating: 83, tmId: 934341 },
    ]
  },

  argentina: {
    name: "Argentina", flag: "🇦🇷", flagCode: "ar", color: "#74acdf", accent: "#fff", textColor: "#43a1db",
    players: [
      { id: 27, number: 1,  firstName: "Emiliano",   lastName: "Martínez",    age: 33, club: "Aston Villa",     position: "GK",  isRare: true,  rating: 75, tmId: 170603 },
      { id: 28, number: 2,  firstName: "Geronimo",   lastName: "Rulli",       age: 34, club: "Marseille",       position: "GK",  isRare: false, rating: 69, tmId: 178282 },
      { id: 29, number: 3,  firstName: "Juan",       lastName: "Musso",       age: 32, club: "Atlético Madrid", position: "GK",  isRare: false, rating: 60, tmId: 0      },
      { id: 30, number: 4,  firstName: "Cristian",   lastName: "Romero",      age: 28, club: "Tottenham",       position: "CB",  isRare: true,  rating: 86, tmId: 384498 },
      { id: 31, number: 5,  firstName: "Marcos",     lastName: "Senesi",      age: 29, club: "Bournemouth",     position: "CB",  isRare: false, rating: 79, tmId: 0      },
      { id: 32, number: 6,  firstName: "Tomás",      lastName: "Palacios",    age: 23, club: "Estudiantes",     position: "CB",  isRare: false, rating: 67, tmId: 0      },
      { id: 33, number: 7,  firstName: "Nahuel",     lastName: "Molina",      age: 28, club: "Atlético Madrid", position: "RB",  isRare: false, rating: 75, tmId: 393561 },
      { id: 34, number: 8,  firstName: "Agustín",    lastName: "Giay",        age: 22, club: "Palmeiras",       position: "RB",  isRare: false, rating: 71, tmId: 0      },
      { id: 35, number: 9,  firstName: "Nicolás",    lastName: "Tagliafico",  age: 33, club: "Lyon",            position: "LB",  isRare: false, rating: 65, tmId: 228702 },
      { id: 36, number: 10, firstName: "Gabriel",    lastName: "Rojas",       age: 28, club: "Racing Club",     position: "LB",  isRare: false, rating: 63, tmId: 0      },
      { id: 37, number: 11, firstName: "Máximo",     lastName: "Perrone",     age: 23, club: "Como",            position: "CDM", isRare: false, rating: 81, tmId: 0      },
      { id: 38, number: 12, firstName: "Leandro",    lastName: "Paredes",     age: 31, club: "Boca Juniors",    position: "CDM", isRare: false, rating: 65, tmId: 149978 },
      { id: 39, number: 13, firstName: "Enzo",       lastName: "Fernández",   age: 25, club: "Chelsea",         position: "CM",  isRare: true,  rating: 92, tmId: 612682 },
      { id: 40, number: 14, firstName: "Alexis",     lastName: "Mac Allister",age: 27, club: "Liverpool",       position: "CM",  isRare: true,  rating: 91, tmId: 462740 },
      { id: 41, number: 15, firstName: "Valentín",   lastName: "Barco",       age: 21, club: "Strasbourg",      position: "CM",  isRare: false, rating: 83, tmId: 0      },
      { id: 42, number: 16, firstName: "Exequiel",   lastName: "Palacios",    age: 27, club: "Leverkusen",      position: "CM",  isRare: false, rating: 81, tmId: 361248 },
      { id: 43, number: 17, firstName: "Rodrigo",    lastName: "De Paul",     age: 32, club: "Inter Miami",     position: "CM",  isRare: true,  rating: 75, tmId: 175481 },
      { id: 44, number: 18, firstName: "Nico",       lastName: "Paz",         age: 21, club: "Como",            position: "CAM", isRare: true,  rating: 89, tmId: 0      },
      { id: 45, number: 19, firstName: "Thiago",     lastName: "Almada",      age: 25, club: "Atlético Madrid", position: "LW",  isRare: false, rating: 78, tmId: 656919 },
      { id: 46, number: 20, firstName: "Nicolás",    lastName: "González",    age: 28, club: "Atlético Madrid", position: "LW",  isRare: false, rating: 79, tmId: 357757 },
      { id: 47, number: 21, firstName: "Franco",     lastName: "Mastantuono", age: 18, club: "Real Madrid",     position: "RW",  isRare: true,  rating: 85, tmId: 0      },
      { id: 48, number: 22, firstName: "Giuliano",   lastName: "Simeone",     age: 23, club: "Atlético Madrid", position: "RW",  isRare: false, rating: 84, tmId: 0      },
      { id: 49, number: 23, firstName: "Lionel",     lastName: "Messi",       age: 38, club: "Inter Miami",     position: "RW",  isRare: true,  rating: 75, tmId: 28003  },
      { id: 50, number: 24, firstName: "Gianluca",   lastName: "Prestianni",  age: 20, club: "Benfica",         position: "RW",  isRare: false, rating: 73, tmId: 0      },
      { id: 51, number: 25, firstName: "Julián",     lastName: "Álvarez",     age: 26, club: "Atlético Madrid", position: "ST",  isRare: true,  rating: 92, tmId: 581118 },
      { id: 52, number: 26, firstName: "José Manuel",lastName: "López",       age: 25, club: "Palmeiras",       position: "ST",  isRare: false, rating: 79, tmId: 0      },
    ]
  },

  france: {
    name: "France", flag: "🇫🇷", flagCode: "fr", color: "#002395", accent: "#ed2939", textColor: "#fff",
    players: [
      { id: 53, number: 1,  firstName: "Mike",       lastName: "Maignan",     age: 30, club: "AC Milan",        position: "GK",  isRare: true,  rating: 80, tmId: 200512 },
      { id: 54, number: 2,  firstName: "Robin",      lastName: "Risser",      age: 21, club: "RC Lens",         position: "GK",  isRare: false, rating: 80, tmId: 0      },
      { id: 55, number: 3,  firstName: "Brice",      lastName: "Samba",       age: 32, club: "Rennes",          position: "GK",  isRare: false, rating: 69, tmId: 202906 },
      { id: 56, number: 4,  firstName: "William",    lastName: "Saliba",      age: 25, club: "Arsenal",         position: "CB",  isRare: true,  rating: 92, tmId: 512208 },
      { id: 57, number: 5,  firstName: "Dayot",      lastName: "Upamecano",   age: 27, club: "Bayern Munich",   position: "CB",  isRare: true,  rating: 89, tmId: 346843 },
      { id: 58, number: 6,  firstName: "Ibrahima",   lastName: "Konaté",      age: 26, club: "Liverpool",       position: "CB",  isRare: false, rating: 86, tmId: 398076 },
      { id: 59, number: 7,  firstName: "Maxence",    lastName: "Lacroix",     age: 26, club: "Crystal Palace",  position: "CB",  isRare: false, rating: 84, tmId: 536742 },
      { id: 60, number: 8,  firstName: "Jules",      lastName: "Koundé",      age: 27, club: "Barcelona",       position: "RB",  isRare: false, rating: 89, tmId: 370771 },
      { id: 61, number: 9,  firstName: "Malo",       lastName: "Gusto",       age: 23, club: "Chelsea",         position: "RB",  isRare: false, rating: 83, tmId: 747185 },
      { id: 62, number: 10, firstName: "Theo",       lastName: "Hernández",   age: 28, club: "Al-Hilal",        position: "LB",  isRare: false, rating: 81, tmId: 276946 },
      { id: 63, number: 11, firstName: "Lucas",      lastName: "Hernández",   age: 30, club: "PSG",             position: "LB",  isRare: false, rating: 78, tmId: 299633 },
      { id: 64, number: 12, firstName: "Lucas",      lastName: "Digne",       age: 32, club: "Aston Villa",     position: "LB",  isRare: false, rating: 69, tmId: 68809  },
      { id: 65, number: 13, firstName: "Aurélien",   lastName: "Tchouaméni",  age: 26, club: "Real Madrid",     position: "CDM", isRare: true,  rating: 90, tmId: 580195 },
      { id: 66, number: 14, firstName: "N'Golo",     lastName: "Kanté",       age: 35, club: "Fenerbahce",      position: "CDM", isRare: true,  rating: 63, tmId: 161256 },
      { id: 67, number: 15, firstName: "Warren",     lastName: "Zaïre-Emery", age: 20, club: "PSG",             position: "CM",  isRare: true,  rating: 88, tmId: 864617 },
      { id: 68, number: 16, firstName: "Manu",       lastName: "Koné",        age: 25, club: "Roma",            position: "CM",  isRare: false, rating: 86, tmId: 582679 },
      { id: 69, number: 17, firstName: "Adrien",     lastName: "Rabiot",      age: 31, club: "AC Milan",        position: "CM",  isRare: false, rating: 78, tmId: 176317 },
      { id: 70, number: 18, firstName: "Rayan",      lastName: "Cherki",      age: 22, club: "Man City",        position: "CAM", isRare: true,  rating: 89, tmId: 842858 },
      { id: 71, number: 19, firstName: "Bradley",    lastName: "Barcola",     age: 23, club: "PSG",             position: "LW",  isRare: true,  rating: 89, tmId: 846616 },
      { id: 72, number: 20, firstName: "Michael",    lastName: "Olise",       age: 24, club: "Bayern Munich",   position: "RW",  isRare: true,  rating: 96, tmId: 772614 },
      { id: 73, number: 21, firstName: "Désiré",     lastName: "Doué",        age: 20, club: "PSG",             position: "RW",  isRare: false, rating: 92, tmId: 0      },
      { id: 74, number: 22, firstName: "Maghnes",    lastName: "Akliouche",   age: 24, club: "Monaco",          position: "RW",  isRare: false, rating: 86, tmId: 727826 },
      { id: 75, number: 23, firstName: "Kylian",     lastName: "Mbappé",      age: 27, club: "Real Madrid",     position: "ST",  isRare: true,  rating: 99, tmId: 342229 },
      { id: 76, number: 24, firstName: "Ousmane",    lastName: "Dembélé",     age: 29, club: "PSG",             position: "ST",  isRare: true,  rating: 93, tmId: 339122 },
      { id: 77, number: 25, firstName: "Marcus",     lastName: "Thuram",      age: 28, club: "Inter Milan",     position: "ST",  isRare: false, rating: 86, tmId: 315063 },
      { id: 78, number: 26, firstName: "Jean-Philippe", lastName: "Mateta",  age: 28, club: "Crystal Palace",  position: "ST",  isRare: false, rating: 83, tmId: 291255 },
    ]
  },

  england: {
    name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", flagCode: "gb-eng", color: "#012169", accent: "#c8102e", textColor: "#fff",
    players: [
      { id: 79,  number: 1,  firstName: "Dean",      lastName: "Henderson",   age: 29, club: "Crystal Palace",  position: "GK",  isRare: false, rating: 81, tmId: 205607 },
      { id: 80,  number: 2,  firstName: "James",     lastName: "Trafford",    age: 23, club: "Man City",        position: "GK",  isRare: false, rating: 80, tmId: 795817 },
      { id: 81,  number: 3,  firstName: "Jordan",    lastName: "Pickford",    age: 32, club: "Everton",         position: "GK",  isRare: false, rating: 75, tmId: 148455 },
      { id: 82,  number: 4,  firstName: "Marc",      lastName: "Guéhi",       age: 25, club: "Man City",        position: "CB",  isRare: true,  rating: 89, tmId: 480681 },
      { id: 83,  number: 5,  firstName: "Jarell",    lastName: "Quansah",     age: 23, club: "Leverkusen",      position: "CB",  isRare: false, rating: 85, tmId: 816832 },
      { id: 84,  number: 6,  firstName: "Ezri",      lastName: "Konsa",       age: 28, club: "Aston Villa",     position: "CB",  isRare: false, rating: 84, tmId: 399895 },
      { id: 85,  number: 7,  firstName: "John",      lastName: "Stones",      age: 31, club: "Man City",        position: "CB",  isRare: false, rating: 75, tmId: 167471 },
      { id: 86,  number: 8,  firstName: "Dan",       lastName: "Burn",        age: 34, club: "Newcastle",       position: "CB",  isRare: false, rating: 65, tmId: 144990 },
      { id: 87,  number: 9,  firstName: "Reece",     lastName: "James",       age: 26, club: "Chelsea",         position: "RB",  isRare: true,  rating: 88, tmId: 459609 },
      { id: 88,  number: 10, firstName: "Tino",      lastName: "Livramento",  age: 23, club: "Newcastle",       position: "RB",  isRare: false, rating: 84, tmId: 748555 },
      { id: 89,  number: 11, firstName: "Nico",      lastName: "O'Reilly",    age: 21, club: "Man City",        position: "LB",  isRare: false, rating: 86, tmId: 0      },
      { id: 90,  number: 12, firstName: "Djed",      lastName: "Spence",      age: 25, club: "Tottenham",       position: "LB",  isRare: false, rating: 81, tmId: 529427 },
      { id: 91,  number: 13, firstName: "Declan",    lastName: "Rice",        age: 27, club: "Arsenal",         position: "CM",  isRare: true,  rating: 94, tmId: 357662 },
      { id: 92,  number: 14, firstName: "Kobbie",    lastName: "Mainoo",      age: 21, club: "Man United",      position: "CDM", isRare: true,  rating: 86, tmId: 918958 },
      { id: 93,  number: 15, firstName: "Jordan",    lastName: "Henderson",   age: 35, club: "Brentford",       position: "CDM", isRare: false, rating: 56, tmId: 54681  },
      { id: 94,  number: 16, firstName: "Elliot",    lastName: "Anderson",    age: 23, club: "Nottm Forest",    position: "CM",  isRare: false, rating: 88, tmId: 826543 },
      { id: 95,  number: 17, firstName: "Jude",      lastName: "Bellingham",  age: 22, club: "Real Madrid",     position: "CAM", isRare: true,  rating: 96, tmId: 581678 },
      { id: 96,  number: 18, firstName: "Morgan",    lastName: "Rogers",      age: 23, club: "Aston Villa",     position: "CAM", isRare: true,  rating: 91, tmId: 851700 },
      { id: 97,  number: 19, firstName: "Eberechi",  lastName: "Eze",         age: 27, club: "Arsenal",         position: "CAM", isRare: true,  rating: 88, tmId: 538804 },
      { id: 98,  number: 20, firstName: "Anthony",   lastName: "Gordon",      age: 25, club: "Newcastle",       position: "LW",  isRare: true,  rating: 88, tmId: 537937 },
      { id: 99,  number: 21, firstName: "Marcus",    lastName: "Rashford",    age: 28, club: "Barcelona",       position: "LW",  isRare: true,  rating: 84, tmId: 258923 },
      { id: 100, number: 22, firstName: "Bukayo",    lastName: "Saka",        age: 24, club: "Arsenal",         position: "RW",  isRare: true,  rating: 94, tmId: 433177 },
      { id: 101, number: 23, firstName: "Noni",      lastName: "Madueke",     age: 24, club: "Arsenal",         position: "RW",  isRare: false, rating: 86, tmId: 795800 },
      { id: 102, number: 24, firstName: "Harry",     lastName: "Kane",        age: 32, club: "Bayern Munich",   position: "ST",  isRare: true,  rating: 89, tmId: 132098 },
      { id: 103, number: 25, firstName: "Ollie",     lastName: "Watkins",     age: 30, club: "Aston Villa",     position: "ST",  isRare: false, rating: 81, tmId: 263745 },
      { id: 104, number: 26, firstName: "Ivan",      lastName: "Toney",       age: 30, club: "Al-Ahli",         position: "ST",  isRare: false, rating: 78, tmId: 298958 },
    ]
  },

  spain: {
    name: "Spain", flag: "🇪🇸", flagCode: "es", color: "#c60b1e", accent: "#ffc400", textColor: "#fff",
    players: [
      { id: 105, number: 1,  firstName: "Joan",      lastName: "García",      age: 25, club: "Barcelona",       position: "GK",  isRare: false, rating: 84, tmId: 0      },
      { id: 106, number: 2,  firstName: "David",     lastName: "Raya",        age: 30, club: "Arsenal",         position: "GK",  isRare: false, rating: 83, tmId: 200491 },
      { id: 107, number: 3,  firstName: "Unai",      lastName: "Simón",       age: 28, club: "Athletic Club",   position: "GK",  isRare: false, rating: 80, tmId: 320043 },
      { id: 108, number: 4,  firstName: "Pau",       lastName: "Cubarsí",     age: 19, club: "Barcelona",       position: "CB",  isRare: true,  rating: 91, tmId: 1018862},
      { id: 109, number: 5,  firstName: "Dean",      lastName: "Huijsen",     age: 21, club: "Real Madrid",     position: "CB",  isRare: false, rating: 89, tmId: 0      },
      { id: 110, number: 6,  firstName: "Cristhian", lastName: "Mosquera",    age: 21, club: "Arsenal",         position: "CB",  isRare: false, rating: 83, tmId: 0      },
      { id: 111, number: 7,  firstName: "Aymeric",   lastName: "Laporte",     age: 31, club: "Athletic Club",   position: "CB",  isRare: false, rating: 70, tmId: 171029 },
      { id: 112, number: 8,  firstName: "Pedro",     lastName: "Porro",       age: 26, club: "Tottenham",       position: "RB",  isRare: false, rating: 84, tmId: 453431 },
      { id: 113, number: 9,  firstName: "Marcos",    lastName: "Llorente",    age: 31, club: "Atlético Madrid", position: "RB",  isRare: false, rating: 79, tmId: 0      },
      { id: 114, number: 10, firstName: "Marc",      lastName: "Cucurella",   age: 27, club: "Chelsea",         position: "LB",  isRare: false, rating: 86, tmId: 443834 },
      { id: 115, number: 11, firstName: "Álex",      lastName: "Grimaldo",    age: 30, club: "Leverkusen",      position: "LB",  isRare: false, rating: 79, tmId: 283986 },
      { id: 116, number: 12, firstName: "Martín",    lastName: "Zubimendi",   age: 27, club: "Arsenal",         position: "CDM", isRare: true,  rating: 91, tmId: 463673 },
      { id: 117, number: 13, firstName: "Rodri",     lastName: "",            age: 29, club: "Man City",        position: "CDM", isRare: true,  rating: 89, tmId: 357307 },
      { id: 118, number: 14, firstName: "Pedri",     lastName: "",            age: 23, club: "Barcelona",       position: "CM",  isRare: true,  rating: 96, tmId: 557005 },
      { id: 119, number: 15, firstName: "Carlos",    lastName: "Soler",       age: 29, club: "Real Sociedad",   position: "CM",  isRare: false, rating: 69, tmId: 0      },
      { id: 120, number: 16, firstName: "Pablo",     lastName: "Fornals",     age: 30, club: "Real Betis",      position: "CM",  isRare: false, rating: 69, tmId: 0      },
      { id: 121, number: 17, firstName: "Fermín",    lastName: "López",       age: 23, club: "Barcelona",       position: "CAM", isRare: true,  rating: 93, tmId: 985734 },
      { id: 122, number: 18, firstName: "Dani",      lastName: "Olmo",        age: 28, club: "Barcelona",       position: "CAM", isRare: true,  rating: 88, tmId: 218983 },
      { id: 123, number: 19, firstName: "Álex",      lastName: "Baena",       age: 24, club: "Atlético Madrid", position: "LW",  isRare: true,  rating: 85, tmId: 663682 },
      { id: 124, number: 20, firstName: "Víctor",    lastName: "Muñoz",       age: 22, club: "Osasuna",         position: "LW",  isRare: false, rating: 78, tmId: 0      },
      { id: 125, number: 21, firstName: "Ander",     lastName: "Barrenetxea", age: 24, club: "Real Sociedad",   position: "LW",  isRare: false, rating: 77, tmId: 0      },
      { id: 126, number: 22, firstName: "Lamine",    lastName: "Yamal",       age: 18, club: "Barcelona",       position: "RW",  isRare: true,  rating: 99, tmId: 927944 },
      { id: 127, number: 23, firstName: "Yéremy",    lastName: "Pino",        age: 23, club: "Crystal Palace",  position: "RW",  isRare: false, rating: 83, tmId: 0      },
      { id: 128, number: 24, firstName: "Ferran",    lastName: "Torres",      age: 26, club: "Barcelona",       position: "ST",  isRare: false, rating: 86, tmId: 451288 },
      { id: 129, number: 25, firstName: "Mikel",     lastName: "Oyarzabal",   age: 29, club: "Real Sociedad",   position: "ST",  isRare: true,  rating: 80, tmId: 215617 },
      { id: 130, number: 26, firstName: "Borja",     lastName: "Iglesias",    age: 33, club: "Celta de Vigo",   position: "ST",  isRare: false, rating: 60, tmId: 0      },
    ]
  },

  germany: {
    name: "Germany", flag: "🇩🇪", flagCode: "de", color: "#000000", accent: "#dd0000", textColor: "#fff",
    players: [
      { id: 131, number: 1,  firstName: "Alexander", lastName: "Nübel",       age: 29, club: "Stuttgart",       position: "GK",  isRare: false, rating: 73, tmId: 351619 },
      { id: 132, number: 2,  firstName: "Manuel",    lastName: "Neuer",       age: 40, club: "Bayern Munich",   position: "GK",  isRare: true,  rating: 63, tmId: 17259  },
      { id: 133, number: 3,  firstName: "Oliver",    lastName: "Baumann",     age: 35, club: "Hoffenheim",      position: "GK",  isRare: false, rating: 60, tmId: 65697  },
      { id: 134, number: 4,  firstName: "Nico",      lastName: "Schlotterbeck",age:26, club: "Dortmund",        position: "CB",  isRare: false, rating: 87, tmId: 480381 },
      { id: 135, number: 5,  firstName: "Malick",    lastName: "Thiaw",       age: 24, club: "Newcastle",       position: "CB",  isRare: false, rating: 85, tmId: 594603 },
      { id: 136, number: 6,  firstName: "Jonathan",  lastName: "Tah",         age: 30, club: "Bayern Munich",   position: "CB",  isRare: false, rating: 81, tmId: 180848 },
      { id: 137, number: 7,  firstName: "Waldemar",  lastName: "Anton",       age: 29, club: "Dortmund",        position: "CB",  isRare: false, rating: 77, tmId: 239399 },
      { id: 138, number: 8,  firstName: "Antonio",   lastName: "Rüdiger",     age: 33, club: "Real Madrid",     position: "CB",  isRare: true,  rating: 70, tmId: 140678 },
      { id: 139, number: 9,  firstName: "Nathaniel", lastName: "Brown",       age: 22, club: "Eintracht Frankfurt", position: "LB", isRare: false, rating: 83, tmId: 0 },
      { id: 140, number: 10, firstName: "David",     lastName: "Raum",        age: 28, club: "RB Leipzig",      position: "LB",  isRare: false, rating: 79, tmId: 443255 },
      { id: 141, number: 11, firstName: "Joshua",    lastName: "Kimmich",     age: 31, club: "Bayern Munich",   position: "CDM", isRare: true,  rating: 84, tmId: 161056 },
      { id: 142, number: 12, firstName: "Aleksandar",lastName: "Pavlović",    age: 22, club: "Bayern Munich",   position: "CDM", isRare: true,  rating: 90, tmId: 891462 },
      { id: 143, number: 13, firstName: "Angelo",    lastName: "Stiller",     age: 25, club: "Stuttgart",       position: "CDM", isRare: false, rating: 85, tmId: 566523 },
      { id: 144, number: 14, firstName: "Felix",     lastName: "Nmecha",      age: 25, club: "Dortmund",        position: "CM",  isRare: false, rating: 86, tmId: 526620 },
      { id: 145, number: 15, firstName: "Nadiem",    lastName: "Amiri",       age: 29, club: "Mainz",           position: "CM",  isRare: false, rating: 76, tmId: 193478 },
      { id: 146, number: 16, firstName: "Leon",      lastName: "Goretzka",    age: 31, club: "Bayern Munich",   position: "CM",  isRare: false, rating: 75, tmId: 150225 },
      { id: 147, number: 17, firstName: "Pascal",    lastName: "Groß",        age: 34, club: "Brighton",        position: "CM",  isRare: false, rating: 62, tmId: 185756 },
      { id: 148, number: 18, firstName: "Jamal",     lastName: "Musiala",     age: 23, club: "Bayern Munich",   position: "CAM", isRare: true,  rating: 94, tmId: 580371 },
      { id: 149, number: 19, firstName: "Florian",   lastName: "Wirtz",       age: 23, club: "Liverpool",       position: "CAM", isRare: true,  rating: 93, tmId: 521361 },
      { id: 150, number: 20, firstName: "Lennart",   lastName: "Karl",        age: 18, club: "Bayern Munich",   position: "CAM", isRare: true,  rating: 88, tmId: 0      },
      { id: 151, number: 21, firstName: "Jamie",     lastName: "Leweling",    age: 25, club: "Stuttgart",       position: "RW",  isRare: false, rating: 84, tmId: 509905 },
      { id: 152, number: 22, firstName: "Leroy",     lastName: "Sané",        age: 30, club: "Galatasaray",     position: "RW",  isRare: true,  rating: 78, tmId: 236702 },
      { id: 153, number: 23, firstName: "Nick",      lastName: "Woltemade",   age: 24, club: "Newcastle",       position: "ST",  isRare: false, rating: 89, tmId: 0      },
      { id: 154, number: 24, firstName: "Kai",       lastName: "Havertz",     age: 26, club: "Arsenal",         position: "ST",  isRare: true,  rating: 86, tmId: 383907 },
      { id: 155, number: 25, firstName: "Maximilian",lastName: "Beier",       age: 23, club: "Dortmund",        position: "ST",  isRare: false, rating: 84, tmId: 698024 },
      { id: 156, number: 26, firstName: "Deniz",     lastName: "Undav",       age: 29, club: "Stuttgart",       position: "ST",  isRare: false, rating: 79, tmId: 413348 },
    ]
  },

  portugal: {
    name: "Portugal", flag: "🇵🇹", flagCode: "pt", color: "#006600", accent: "#ff0000", textColor: "#fff",
    players: [
      { id: 157, number: 1,  firstName: "Diogo",     lastName: "Costa",       age: 26, club: "Porto",           position: "GK",  isRare: false, rating: 84, tmId: 428003 },
      { id: 158, number: 2,  firstName: "Rui",       lastName: "Silva",       age: 32, club: "Sporting CP",     position: "GK",  isRare: false, rating: 68, tmId: 246464 },
      { id: 159, number: 3,  firstName: "José",      lastName: "Sá",          age: 33, club: "Wolves",          position: "GK",  isRare: false, rating: 65, tmId: 200488 },
      { id: 160, number: 4,  firstName: "Rúben",     lastName: "Dias",        age: 29, club: "Man City",        position: "CB",  isRare: true,  rating: 88, tmId: 415471 },
      { id: 161, number: 5,  firstName: "Gonçalo",   lastName: "Inácio",      age: 24, club: "Sporting CP",     position: "CB",  isRare: false, rating: 84, tmId: 535992 },
      { id: 162, number: 6,  firstName: "Tomás",     lastName: "Araújo",      age: 24, club: "Benfica",         position: "CB",  isRare: false, rating: 81, tmId: 669217 },
      { id: 163, number: 7,  firstName: "Renato",    lastName: "Veiga",       age: 22, club: "Villarreal",      position: "CB",  isRare: false, rating: 80, tmId: 821478 },
      { id: 164, number: 8,  firstName: "Nuno",      lastName: "Mendes",      age: 23, club: "PSG",             position: "LB",  isRare: true,  rating: 90, tmId: 549982 },
      { id: 165, number: 9,  firstName: "Diogo",     lastName: "Dalot",       age: 27, club: "Man United",      position: "RB",  isRare: false, rating: 81, tmId: 392710 },
      { id: 166, number: 10, firstName: "Matheus",   lastName: "Nunes",       age: 27, club: "Man City",        position: "RB",  isRare: false, rating: 85, tmId: 626498 },
      { id: 167, number: 11, firstName: "João",      lastName: "Cancelo",     age: 31, club: "Barcelona",       position: "RB",  isRare: false, rating: 70, tmId: 203460 },
      { id: 168, number: 12, firstName: "Nélson",    lastName: "Semedo",      age: 32, club: "Fenerbahçe",      position: "RB",  isRare: false, rating: 67, tmId: 214086 },
      { id: 169, number: 13, firstName: "Vitinha",   lastName: "",            age: 26, club: "PSG",             position: "CDM", isRare: true,  rating: 93, tmId: 550645 },
      { id: 170, number: 14, firstName: "Rúben",     lastName: "Neves",       age: 29, club: "Al-Hilal",        position: "CDM", isRare: false, rating: 80, tmId: 241963 },
      { id: 171, number: 15, firstName: "Samú",      lastName: "Costa",       age: 25, club: "Mallorca",        position: "CDM", isRare: false, rating: 75, tmId: 0      },
      { id: 172, number: 16, firstName: "João",      lastName: "Neves",       age: 21, club: "PSG",             position: "CM",  isRare: true,  rating: 93, tmId: 1016878},
      { id: 173, number: 17, firstName: "Bruno",     lastName: "Fernandes",   age: 31, club: "Man United",      position: "CAM", isRare: true,  rating: 84, tmId: 240306 },
      { id: 174, number: 18, firstName: "Francisco", lastName: "Trincão",     age: 26, club: "Sporting CP",     position: "CAM", isRare: false, rating: 83, tmId: 424913 },
      { id: 175, number: 19, firstName: "Bernardo",  lastName: "Silva",       age: 31, club: "Man City",        position: "CAM", isRare: true,  rating: 80, tmId: 219442 },
      { id: 176, number: 20, firstName: "Rafael",    lastName: "Leão",        age: 26, club: "AC Milan",        position: "LW",  isRare: true,  rating: 89, tmId: 451376 },
      { id: 177, number: 21, firstName: "Gonçalo",   lastName: "Guedes",      age: 29, club: "Real Sociedad",   position: "LW",  isRare: false, rating: 67, tmId: 316540 },
      { id: 178, number: 22, firstName: "Pedro",     lastName: "Neto",        age: 26, club: "Chelsea",         position: "RW",  isRare: true,  rating: 88, tmId: 451384 },
      { id: 179, number: 23, firstName: "Francisco", lastName: "Conceição",   age: 23, club: "Juventus",        position: "RW",  isRare: false, rating: 81, tmId: 811794 },
      { id: 180, number: 24, firstName: "João",      lastName: "Félix",       age: 26, club: "Al-Nassr",        position: "CAM", isRare: false, rating: 80, tmId: 461468 },
      { id: 181, number: 25, firstName: "Gonçalo",   lastName: "Ramos",       age: 24, club: "PSG",             position: "ST",  isRare: false, rating: 83, tmId: 681946 },
      { id: 182, number: 26, firstName: "Cristiano", lastName: "Ronaldo",     age: 41, club: "Al-Nassr",        position: "ST",  isRare: true,  rating: 73, tmId: 8198   },
    ]
  },

  netherlands: {
    name: "Netherlands", flag: "🇳🇱", flagCode: "nl", color: "#ff6600", accent: "#003882", textColor: "#fff",
    players: [
      { id: 183, number: 1,  firstName: "Bart",      lastName: "Verbruggen",  age: 23, club: "Brighton",        position: "GK",  isRare: false, rating: 84, tmId: 726304 },
      { id: 184, number: 2,  firstName: "Mark",      lastName: "Flekken",     age: 32, club: "Leverkusen",      position: "GK",  isRare: false, rating: 69, tmId: 160644 },
      { id: 185, number: 3,  firstName: "Justin",    lastName: "Bijlow",      age: 28, club: "Genoa",           position: "GK",  isRare: false, rating: 63, tmId: 0      },
      { id: 186, number: 4,  firstName: "Micky",     lastName: "van de Ven",  age: 25, club: "Tottenham",       position: "CB",  isRare: true,  rating: 89, tmId: 766289 },
      { id: 187, number: 5,  firstName: "Jan Paul",  lastName: "van Hecke",   age: 25, club: "Brighton",        position: "CB",  isRare: false, rating: 83, tmId: 559424 },
      { id: 188, number: 6,  firstName: "Virgil",    lastName: "van Dijk",    age: 34, club: "Liverpool",       position: "CB",  isRare: true,  rating: 77, tmId: 139758 },
      { id: 189, number: 7,  firstName: "Nathan",    lastName: "Aké",         age: 31, club: "Man City",        position: "CB",  isRare: false, rating: 75, tmId: 185762 },
      { id: 190, number: 8,  firstName: "Stefan",    lastName: "de Vrij",     age: 34, club: "Inter Milan",     position: "CB",  isRare: false, rating: 62, tmId: 105694 },
      { id: 191, number: 9,  firstName: "Jorrel",    lastName: "Hato",        age: 20, club: "Chelsea",         position: "LB",  isRare: false, rating: 83, tmId: 0      },
      { id: 192, number: 10, firstName: "Jeremie",   lastName: "Frimpong",    age: 25, club: "Liverpool",       position: "RB",  isRare: false, rating: 83, tmId: 0      },
      { id: 193, number: 11, firstName: "Denzel",    lastName: "Dumfries",    age: 30, club: "Inter Milan",     position: "RB",  isRare: false, rating: 80, tmId: 275167 },
      { id: 194, number: 12, firstName: "Lutsharel", lastName: "Geertruida",  age: 25, club: "Sunderland",      position: "RB",  isRare: false, rating: 78, tmId: 0      },
      { id: 195, number: 13, firstName: "Ryan",      lastName: "Gravenberch", age: 24, club: "Liverpool",       position: "CDM", isRare: true,  rating: 92, tmId: 508398 },
      { id: 196, number: 14, firstName: "Jerdy",     lastName: "Schouten",    age: 29, club: "PSV",             position: "CDM", isRare: false, rating: 79, tmId: 249671 },
      { id: 197, number: 15, firstName: "Teun",      lastName: "Koopmeiners", age: 28, club: "Juventus",        position: "CDM", isRare: true,  rating: 78, tmId: 418460 },
      { id: 198, number: 16, firstName: "Tijjani",   lastName: "Reijnders",   age: 27, club: "Man City",        position: "CM",  isRare: true,  rating: 88, tmId: 512229 },
      { id: 199, number: 17, firstName: "Kees",      lastName: "Smit",        age: 20, club: "AZ Alkmaar",      position: "CM",  isRare: false, rating: 80, tmId: 0      },
      { id: 200, number: 18, firstName: "Quinten",   lastName: "Timber",      age: 24, club: "Marseille",       position: "CM",  isRare: false, rating: 80, tmId: 659673 },
      { id: 201, number: 19, firstName: "Luciano",   lastName: "Valente",     age: 22, club: "Feyenoord",       position: "CM",  isRare: false, rating: 77, tmId: 0      },
      { id: 202, number: 20, firstName: "Xavi",      lastName: "Simons",      age: 23, club: "Tottenham",       position: "CAM", isRare: true,  rating: 86, tmId: 640705 },
      { id: 203, number: 21, firstName: "Cody",      lastName: "Gakpo",       age: 27, club: "Liverpool",       position: "LW",  isRare: true,  rating: 89, tmId: 546750 },
      { id: 204, number: 22, firstName: "Noa",       lastName: "Lang",        age: 26, club: "Galatasaray",     position: "LW",  isRare: false, rating: 79, tmId: 487153 },
      { id: 205, number: 23, firstName: "Donyell",   lastName: "Malen",       age: 27, club: "Roma",            position: "ST",  isRare: false, rating: 83, tmId: 369007 },
      { id: 206, number: 24, firstName: "Brian",     lastName: "Brobbey",     age: 24, club: "Sunderland",      position: "ST",  isRare: false, rating: 80, tmId: 557008 },
      { id: 207, number: 25, firstName: "Wout",      lastName: "Weghorst",    age: 33, club: "Ajax",            position: "ST",  isRare: false, rating: 58, tmId: 208483 },
      { id: 208, number: 26, firstName: "Memphis",   lastName: "Depay",       age: 32, club: "Corinthians",     position: "ST",  isRare: true,  rating: 60, tmId: 96910  },
    ]
  },
};

// Flat list of all players for pack draws
const ALL_PLAYERS = Object.entries(TEAMS).flatMap(([teamId, team]) =>
  team.players.map(p => ({ ...p, teamId, teamName: team.name, teamFlag: team.flag, teamColor: team.color, teamAccent: team.accent }))
);

const TOTAL_STICKERS = ALL_PLAYERS.length; // 208
