const TEAMS = {
  brazil: {
    name: "Brazil", flag: "🇧🇷", flagCode: "br", color: "#009c3b", accent: "#ffdf00", textColor: "#fff",
    players: [
      { id: 1,  number: 1,  firstName: "Alisson",    lastName: "Becker",      age: 33, club: "Liverpool",       position: "GK",  isRare: false, tmId: 105470,  rating: 80 },
      { id: 2,  number: 2,  firstName: "Ederson",    lastName: "",            age: 32, club: "Fenerbahce",      position: "GK",  isRare: false, tmId: 238223,  rating: 78 },
      { id: 3,  number: 3,  firstName: "Weverton",   lastName: "",            age: 38, club: "Palmeiras",       position: "GK",  isRare: false, tmId: 69400,   rating: 65 },
      { id: 4,  number: 4,  firstName: "Marquinhos", lastName: "",            age: 32, club: "PSG",             position: "CB",  isRare: true,  tmId: 181767,  rating: 82 },
      { id: 5,  number: 5,  firstName: "Gabriel",    lastName: "Magalhães",   age: 28, club: "Arsenal",         position: "CB",  isRare: false, tmId: 435338,  rating: 89 },
      { id: 6,  number: 6,  firstName: "Bremer",     lastName: "",            age: 29, club: "Juventus",        position: "CB",  isRare: false, tmId: 516716,  rating: 85 },
      { id: 7,  number: 7,  firstName: "Roger",      lastName: "Ibañez",      age: 27, club: "Al-Ahli",         position: "CB",  isRare: false, tmId: 524481,  rating: 71 },
      { id: 8,  number: 8,  firstName: "Léo",        lastName: "Pereira",     age: 29, club: "Flamengo",        position: "CB",  isRare: false, tmId: 288431,  rating: 73 },
      { id: 9,  number: 9,  firstName: "Wesley",     lastName: "",            age: 22, club: "Roma",            position: "RB",  isRare: false, tmId: 964580,  rating: 80 },
      { id: 10, number: 10, firstName: "Danilo",     lastName: "",            age: 34, club: "Flamengo",        position: "RB",  isRare: false, tmId: 145707,  rating: 60 },
      { id: 11, number: 11, firstName: "Alex",       lastName: "Sandro",      age: 35, club: "Flamengo",        position: "LB",  isRare: false, tmId: 79960,   rating: 60 },
      { id: 12, number: 12, firstName: "Douglas",    lastName: "Santos",      age: 32, club: "Zenit",           position: "LB",  isRare: false, tmId: 220793,  rating: 63 },
      { id: 13, number: 13, firstName: "Bruno",      lastName: "Guimarães",   age: 28, club: "Newcastle",       position: "CM",  isRare: true,  tmId: 520624,  rating: 91 },
      { id: 14, number: 14, firstName: "Casemiro",   lastName: "",            age: 34, club: "Man United",      position: "CDM", isRare: true,  tmId: 16306,   rating: 78 },
      { id: 15, number: 15, firstName: "Danilo",     lastName: "Santos",      age: 29, club: "Botafogo",        position: "CM",  isRare: false, tmId: 808509,  rating: 69 },
      { id: 16, number: 16, firstName: "Fabinho",    lastName: "",            age: 32, club: "Al-Ittihad",      position: "CDM", isRare: false, tmId: 225693,  rating: 65 },
      { id: 17, number: 17, firstName: "Lucas",      lastName: "Paquetá",     age: 28, club: "Flamengo",        position: "CAM", isRare: true,  tmId: 444523,  rating: 86 },
      { id: 18, number: 18, firstName: "Raphinha",   lastName: "",            age: 29, club: "Barcelona",       position: "RW",  isRare: true,  tmId: 411295,  rating: 92 },
      { id: 19, number: 19, firstName: "Neymar",     lastName: "",            age: 34, club: "Santos",          position: "LW",  isRare: true,  tmId: 68290,   rating: 75 },
      { id: 20, number: 20, firstName: "Vinícius",   lastName: "Jr.",         age: 25, club: "Real Madrid",     position: "LW",  isRare: true,  tmId: 371998,  rating: 99 },
      { id: 21, number: 21, firstName: "Luiz",       lastName: "Henrique",    age: 25, club: "Zenit",           position: "RW",  isRare: false, tmId: 800175,  rating: 69 },
      { id: 22, number: 22, firstName: "Matheus",    lastName: "Cunha",       age: 27, club: "Man United",      position: "ST",  isRare: true,  tmId: 517894,  rating: 89 },
      { id: 23, number: 23, firstName: "Gabriel",    lastName: "Martinelli",  age: 24, club: "Arsenal",         position: "LW",  isRare: true,  tmId: 655488,  rating: 89 },
      { id: 24, number: 24, firstName: "Igor",       lastName: "Thiago",      age: 24, club: "Brentford",       position: "ST",  isRare: false, tmId: 739443,  rating: 78 },
      { id: 25, number: 25, firstName: "Endrick",    lastName: "",            age: 19, club: "Lyon",            position: "ST",  isRare: true,  tmId: 971570,  rating: 88 },
      { id: 26, number: 26, firstName: "Rayan",      lastName: "",            age: 18, club: "Bournemouth",     position: "RW",  isRare: false, tmId: 1012564, rating: 78 },
    ]
  },

  argentina: {
    name: "Argentina", flag: "🇦🇷", flagCode: "ar", color: "#74acdf", accent: "#fff", textColor: "#43a1db",
    players: [
      { id: 27, number: 1,  firstName: "Emiliano",   lastName: "Martínez",        age: 33, club: "Aston Villa",          position: "GK",  isRare: true,  tmId: 111873,  rating: 82 },
      { id: 28, number: 2,  firstName: "Gerónimo",   lastName: "Rulli",           age: 33, club: "Olympique Marseille",  position: "GK",  isRare: false, tmId: 229604,  rating: 69 },
      { id: 29, number: 3,  firstName: "Juan",       lastName: "Musso",           age: 31, club: "Atlético de Madrid",  position: "GK",  isRare: false, tmId: 242359,  rating: 71 },
      { id: 30, number: 4,  firstName: "Cristian",   lastName: "Romero",          age: 27, club: "Tottenham",           position: "CB",  isRare: true,  tmId: 355915,  rating: 88 },
      { id: 31, number: 5,  firstName: "Marcos",     lastName: "Senesi",          age: 28, club: "AFC Bournemouth",     position: "CB",  isRare: false, tmId: 469781,  rating: 78 },
      { id: 32, number: 6,  firstName: "Tomás",      lastName: "Palacios",        age: 22, club: "Club Estudiantes",    position: "CB",  isRare: false, tmId: 993645,  rating: 69 },
      { id: 33, number: 7,  firstName: "Lucas",      lastName: "Martínez Quarta", age: 28, club: "CA River Plate",      position: "CB",  isRare: false, tmId: 373373,  rating: 75 },
      { id: 34, number: 8,  firstName: "Nicolás",    lastName: "Otamendi",        age: 38, club: "SL Benfica",          position: "CB",  isRare: false, tmId: 54781,   rating: 65 },
      { id: 35, number: 9,  firstName: "Nicolás",    lastName: "Tagliafico",      age: 33, club: "Olympique Lyon",      position: "LB",  isRare: false, tmId: 131225,  rating: 66 },
      { id: 36, number: 10, firstName: "Gabriel",    lastName: "Rojas",           age: 26, club: "Racing Club",         position: "LB",  isRare: false, tmId: 471639,  rating: 65 },
      { id: 37, number: 11, firstName: "Marcos",     lastName: "Acuña",           age: 33, club: "CA River Plate",      position: "LB",  isRare: false, tmId: 60410,   rating: 65 },
      { id: 38, number: 12, firstName: "Nahuel",     lastName: "Molina",          age: 27, club: "Atlético de Madrid",  position: "RB",  isRare: false, tmId: 424042,  rating: 80 },
      { id: 39, number: 13, firstName: "Agustín",    lastName: "Giay",            age: 22, club: "Palmeiras",           position: "RB",  isRare: false, tmId: 849582,  rating: 73 },
      { id: 40, number: 14, firstName: "Máximo",     lastName: "Perrone",         age: 22, club: "Como 1907",           position: "CDM", isRare: false, tmId: 668547,  rating: 77 },
      { id: 41, number: 15, firstName: "Leandro",    lastName: "Paredes",         age: 31, club: "CA Boca Juniors",     position: "CDM", isRare: false, tmId: 166237,  rating: 66 },
      { id: 42, number: 16, firstName: "Enzo",       lastName: "Fernández",       age: 25, club: "Chelsea",             position: "CM",  isRare: true,  tmId: 648195,  rating: 93 },
      { id: 43, number: 17, firstName: "Alexis",     lastName: "Mac Allister",    age: 26, club: "Liverpool",           position: "CM",  isRare: true,  tmId: 534033,  rating: 91 },
      { id: 44, number: 18, firstName: "Valentín",   lastName: "Barco",           age: 21, club: "RC Strasbourg",       position: "LB",  isRare: false, tmId: 849410,  rating: 73 },
      { id: 45, number: 19, firstName: "Exequiel",   lastName: "Palacios",        age: 26, club: "Bayer Leverkusen",    position: "CM",  isRare: false, tmId: 401578,  rating: 80 },
      { id: 46, number: 20, firstName: "Rodrigo",    lastName: "De Paul",         age: 31, club: "Inter Miami",         position: "CM",  isRare: true,  tmId: 255901,  rating: 78 },
      { id: 47, number: 21, firstName: "Nico",       lastName: "Paz",             age: 21, club: "Como 1907",           position: "CAM", isRare: false, tmId: 948294,  rating: 84 },
      { id: 48, number: 22, firstName: "Nico",       lastName: "González",        age: 27, club: "Atlético de Madrid",  position: "LW",  isRare: false, tmId: 486031,  rating: 83 },
      { id: 49, number: 23, firstName: "Thiago",     lastName: "Almada",          age: 25, club: "Atlético de Madrid",  position: "CAM", isRare: false, tmId: 576028,  rating: 80 },
      { id: 50, number: 24, firstName: "Franco",     lastName: "Mastantuono",     age: 18, club: "Real Madrid",         position: "CAM", isRare: true,  tmId: 1057316, rating: 91 },
      { id: 51, number: 25, firstName: "Giuliano",   lastName: "Simeone",         age: 22, club: "Atlético de Madrid",  position: "RW",  isRare: false, tmId: 742201,  rating: 78 },
      { id: 52, number: 26, firstName: "Lionel",     lastName: "Messi",           age: 38, club: "Inter Miami",         position: "RW",  isRare: true,  tmId: 28003,   rating: 78 },
    ]
  },

  france: {
    name: "France", flag: "🇫🇷", flagCode: "fr", color: "#002395", accent: "#ed2939", textColor: "#fff",
    players: [
      { id: 53, number: 1,  firstName: "Mike",          lastName: "Maignan",      age: 30, club: "AC Milan",        position: "GK",  isRare: true,  tmId: 182906, rating: 84 },
      { id: 54, number: 2,  firstName: "Brice",         lastName: "Samba",        age: 32, club: "Rennes",          position: "GK",  isRare: false, tmId: 191056, rating: 73 },
      { id: 55, number: 3,  firstName: "Robin",         lastName: "Risser",       age: 21, club: "RC Lens",         position: "GK",  isRare: false, tmId: 743515, rating: 69 },
      { id: 56, number: 4,  firstName: "William",       lastName: "Saliba",       age: 25, club: "Arsenal",         position: "CB",  isRare: true,  tmId: 495666, rating: 92 },
      { id: 57, number: 5,  firstName: "Dayot",         lastName: "Upamecano",    age: 27, club: "Bayern Munich",   position: "CB",  isRare: true,  tmId: 344695, rating: 88 },
      { id: 58, number: 6,  firstName: "Ibrahima",      lastName: "Konaté",       age: 26, club: "Liverpool",       position: "CB",  isRare: false, tmId: 357119, rating: 87 },
      { id: 59, number: 7,  firstName: "Jules",         lastName: "Koundé",       age: 27, club: "Barcelona",       position: "RB",  isRare: false, tmId: 411975, rating: 88 },
      { id: 60, number: 8,  firstName: "Malo",          lastName: "Gusto",        age: 23, club: "Chelsea",         position: "RB",  isRare: false, tmId: 620322, rating: 83 },
      { id: 61, number: 9,  firstName: "Theo",          lastName: "Hernández",    age: 28, club: "Al-Hilal",        position: "LB",  isRare: true,  tmId: 339808, rating: 85 },
      { id: 62, number: 10, firstName: "Lucas",         lastName: "Hernández",    age: 30, club: "PSG",             position: "LB",  isRare: false, tmId: 281963, rating: 78 },
      { id: 63, number: 11, firstName: "Maxence",       lastName: "Lacroix",      age: 26, club: "Crystal Palace",  position: "CB",  isRare: false, tmId: 434224, rating: 78 },
      { id: 64, number: 12, firstName: "Lucas",         lastName: "Digne",        age: 32, club: "Aston Villa",     position: "LB",  isRare: false, tmId: 126664, rating: 69 },
      { id: 65, number: 13, firstName: "Aurélien",      lastName: "Tchouaméni",   age: 26, club: "Real Madrid",     position: "CDM", isRare: true,  tmId: 413112, rating: 91 },
      { id: 66, number: 14, firstName: "Warren",        lastName: "Zaïre-Emery",  age: 20, club: "PSG",             position: "CM",  isRare: true,  tmId: 810092, rating: 91 },
      { id: 67, number: 15, firstName: "Adrien",        lastName: "Rabiot",       age: 31, club: "AC Milan",        position: "CM",  isRare: false, tmId: 182913, rating: 78 },
      { id: 68, number: 16, firstName: "N'Golo",        lastName: "Kanté",        age: 35, club: "Fenerbahce",      position: "CDM", isRare: true,  tmId: 225083, rating: 75 },
      { id: 69, number: 17, firstName: "Manu",          lastName: "Koné",         age: 25, club: "Roma",            position: "CM",  isRare: false, tmId: 624690, rating: 82 },
      { id: 70, number: 18, firstName: "Kylian",        lastName: "Mbappé",       age: 27, club: "Real Madrid",     position: "ST",  isRare: true,  tmId: 342229, rating: 98 },
      { id: 71, number: 19, firstName: "Ousmane",       lastName: "Dembélé",      age: 29, club: "PSG",             position: "RW",  isRare: true,  tmId: 288230, rating: 89 },
      { id: 72, number: 20, firstName: "Marcus",        lastName: "Thuram",       age: 28, club: "Inter Milan",     position: "ST",  isRare: true,  tmId: 318528, rating: 91 },
      { id: 73, number: 21, firstName: "Bradley",       lastName: "Barcola",      age: 23, club: "PSG",             position: "LW",  isRare: true,  tmId: 708265, rating: 91 },
      { id: 74, number: 22, firstName: "Michael",       lastName: "Olise",        age: 24, club: "Bayern Munich",   position: "RW",  isRare: true,  tmId: 566723, rating: 91 },
      { id: 75, number: 23, firstName: "Désiré",        lastName: "Doué",         age: 20, club: "PSG",             position: "LW",  isRare: false, tmId: 914562, rating: 88 },
      { id: 76, number: 24, firstName: "Rayan",         lastName: "Cherki",       age: 22, club: "PSG",             position: "CAM", isRare: true,  tmId: 607223, rating: 89 },
      { id: 77, number: 25, firstName: "Maghnes",       lastName: "Akliouche",    age: 24, club: "Monaco",          position: "LW",  isRare: false, tmId: 745200, rating: 80 },
      { id: 78, number: 26, firstName: "Jean-Philippe", lastName: "Mateta",       age: 28, club: "Crystal Palace",  position: "ST",  isRare: false, tmId: 420002, rating: 82 },
    ]
  },

  england: {
    name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", flagCode: "gb-eng", color: "#012169", accent: "#c8102e", textColor: "#fff",
    players: [
      { id: 79,  number: 1,  firstName: "Jordan",    lastName: "Pickford",    age: 32, club: "Everton",         position: "GK",  isRare: false, tmId: 148455, rating: 78 },
      { id: 80,  number: 2,  firstName: "Dean",      lastName: "Henderson",   age: 29, club: "Crystal Palace",  position: "GK",  isRare: false, tmId: 205607, rating: 75 },
      { id: 81,  number: 3,  firstName: "James",     lastName: "Trafford",    age: 23, club: "Man City",        position: "GK",  isRare: false, tmId: 795817, rating: 78 },
      { id: 82,  number: 4,  firstName: "John",      lastName: "Stones",      age: 32, club: "Man City",        position: "CB",  isRare: false, tmId: 167471, rating: 82 },
      { id: 83,  number: 5,  firstName: "Marc",      lastName: "Guéhi",       age: 25, club: "Crystal Palace",  position: "CB",  isRare: false, tmId: 480681, rating: 87 },
      { id: 84,  number: 6,  firstName: "Reece",     lastName: "James",       age: 26, club: "Chelsea",         position: "RB",  isRare: false, tmId: 459609, rating: 86 },
      { id: 85,  number: 7,  firstName: "Ezri",      lastName: "Konsa",       age: 28, club: "Aston Villa",     position: "CB",  isRare: false, tmId: 399895, rating: 83 },
      { id: 86,  number: 8,  firstName: "Jarell",    lastName: "Quansah",     age: 22, club: "Leverkusen",      position: "CB",  isRare: false, tmId: 816832, rating: 78 },
      { id: 87,  number: 9,  firstName: "Dan",       lastName: "Burn",        age: 34, club: "Newcastle",       position: "CB",  isRare: false, tmId: 144990, rating: 69 },
      { id: 88,  number: 10, firstName: "Djed",      lastName: "Spence",      age: 26, club: "Tottenham",       position: "RB",  isRare: false, tmId: 529427, rating: 71 },
      { id: 89,  number: 11, firstName: "Tino",      lastName: "Livramento",  age: 23, club: "Newcastle",       position: "RB",  isRare: false, tmId: 748555, rating: 80 },
      { id: 90,  number: 12, firstName: "Declan",    lastName: "Rice",        age: 27, club: "Arsenal",         position: "CDM", isRare: true,  tmId: 357662, rating: 93 },
      { id: 91,  number: 13, firstName: "Jude",      lastName: "Bellingham",  age: 22, club: "Real Madrid",     position: "CAM", isRare: true,  tmId: 581678, rating: 98 },
      { id: 92,  number: 14, firstName: "Kobbie",    lastName: "Mainoo",      age: 21, club: "Man United",      position: "CM",  isRare: true,  tmId: 918958, rating: 88 },
      { id: 93,  number: 15, firstName: "Eberechi",  lastName: "Eze",         age: 27, club: "Arsenal",         position: "CAM", isRare: false, tmId: 538804, rating: 87 },
      { id: 94,  number: 16, firstName: "Elliot",    lastName: "Anderson",    age: 23, club: "Nottm Forest",    position: "CM",  isRare: false, tmId: 826543, rating: 80 },
      { id: 95,  number: 17, firstName: "Jordan",    lastName: "Henderson",   age: 35, club: "Brentford",       position: "CM",  isRare: false, tmId: 54681,  rating: 65 },
      { id: 96,  number: 18, firstName: "Morgan",    lastName: "Rogers",      age: 23, club: "Aston Villa",     position: "CM",  isRare: false, tmId: 851700, rating: 80 },
      { id: 97,  number: 19, firstName: "Nico",      lastName: "O'Reilly",    age: 21, club: "Man City",        position: "CM",  isRare: false, tmId: 0,      rating: 71 },
      { id: 98,  number: 20, firstName: "Harry",     lastName: "Kane",        age: 32, club: "Bayern Munich",   position: "ST",  isRare: true,  tmId: 132098, rating: 93 },
      { id: 99,  number: 21, firstName: "Bukayo",    lastName: "Saka",        age: 24, club: "Arsenal",         position: "RW",  isRare: true,  tmId: 433177, rating: 96 },
      { id: 100, number: 22, firstName: "Marcus",    lastName: "Rashford",    age: 28, club: "Barcelona",       position: "LW",  isRare: true,  tmId: 258923, rating: 86 },
      { id: 101, number: 23, firstName: "Ollie",     lastName: "Watkins",     age: 30, club: "Aston Villa",     position: "ST",  isRare: false, tmId: 263745, rating: 87 },
      { id: 102, number: 24, firstName: "Anthony",   lastName: "Gordon",      age: 25, club: "Newcastle",       position: "LW",  isRare: false, tmId: 537937, rating: 86 },
      { id: 103, number: 25, firstName: "Ivan",      lastName: "Toney",       age: 30, club: "Al-Ahli",         position: "ST",  isRare: false, tmId: 298958, rating: 78 },
      { id: 104, number: 26, firstName: "Noni",      lastName: "Madueke",     age: 24, club: "Chelsea",         position: "RW",  isRare: false, tmId: 795800, rating: 84 },
    ]
  },

  spain: {
    name: "Spain", flag: "🇪🇸", flagCode: "es", color: "#c60b1e", accent: "#ffc400", textColor: "#fff",
    players: [
      { id: 105, number: 1,  firstName: "Joan",      lastName: "García",      age: 25, club: "Espanyol",        position: "GK",  isRare: false, tmId: 561613,  rating: 78 },
      { id: 106, number: 2,  firstName: "David",     lastName: "Raya",        age: 30, club: "Arsenal",         position: "GK",  isRare: false, tmId: 262749,  rating: 82 },
      { id: 107, number: 3,  firstName: "Unai",      lastName: "Simón",       age: 28, club: "Athletic Club",   position: "GK",  isRare: false, tmId: 262396,  rating: 78 },
      { id: 108, number: 4,  firstName: "Álex",      lastName: "Remiro",      age: 31, club: "Real Sociedad",   position: "GK",  isRare: false, tmId: 212862,  rating: 75 },
      { id: 109, number: 5,  firstName: "Pau",       lastName: "Cubarsí",     age: 19, club: "Barcelona",       position: "CB",  isRare: true,  tmId: 962110,  rating: 91 },
      { id: 110, number: 6,  firstName: "Dean",      lastName: "Huijsen",     age: 21, club: "Real Madrid",     position: "CB",  isRare: false, tmId: 890290,  rating: 85 },
      { id: 111, number: 7,  firstName: "Cristhian", lastName: "Mosquera",    age: 21, club: "Valencia",        position: "CB",  isRare: false, tmId: 646750,  rating: 75 },
      { id: 112, number: 8,  firstName: "Aymeric",   lastName: "Laporte",     age: 31, club: "Al-Nassr",        position: "CB",  isRare: false, tmId: 176553,  rating: 71 },
      { id: 113, number: 9,  firstName: "Marc",      lastName: "Cucurella",   age: 27, club: "Chelsea",         position: "LB",  isRare: false, tmId: 284857,  rating: 83 },
      { id: 114, number: 10, firstName: "Alejandro", lastName: "Grimaldo",    age: 30, club: "Leverkusen",      position: "LB",  isRare: false, tmId: 193082,  rating: 83 },
      { id: 115, number: 11, firstName: "Pedro",     lastName: "Porro",       age: 26, club: "Tottenham",       position: "RB",  isRare: false, tmId: 553875,  rating: 83 },
      { id: 116, number: 12, firstName: "Marcos",    lastName: "Llorente",    age: 31, club: "Atlético Madrid", position: "RB",  isRare: false, tmId: 282411,  rating: 78 },
      { id: 117, number: 13, firstName: "Martín",    lastName: "Zubimendi",   age: 27, club: "Arsenal",         position: "CDM", isRare: false, tmId: 423440,  rating: 88 },
      { id: 118, number: 14, firstName: "Rodri",     lastName: "",            age: 29, club: "Man City",        position: "CDM", isRare: true,  tmId: 357565,  rating: 93 },
      { id: 119, number: 15, firstName: "Pedri",     lastName: "",            age: 23, club: "Barcelona",       position: "CM",  isRare: true,  tmId: 683840,  rating: 93 },
      { id: 120, number: 16, firstName: "Carlos",    lastName: "Soler",       age: 29, club: "PSG",             position: "CM",  isRare: false, tmId: 372246,  rating: 78 },
      { id: 121, number: 17, firstName: "Pablo",     lastName: "Fornals",     age: 30, club: "Real Betis",      position: "CM",  isRare: false, tmId: 357885,  rating: 75 },
      { id: 122, number: 18, firstName: "Fermín",    lastName: "López",       age: 23, club: "Barcelona",       position: "CAM", isRare: true,  tmId: 636703,  rating: 85 },
      { id: 123, number: 19, firstName: "Dani",      lastName: "Olmo",        age: 28, club: "Barcelona",       position: "CAM", isRare: true,  tmId: 293385,  rating: 89 },
      { id: 124, number: 20, firstName: "Álex",      lastName: "Baena",       age: 24, club: "Villarreal",      position: "LW",  isRare: false, tmId: 548111,  rating: 82 },
      { id: 125, number: 21, firstName: "Víctor",    lastName: "Muñoz",       age: 22, club: "Girona",          position: "LW",  isRare: false, tmId: 935231,  rating: 71 },
      { id: 126, number: 22, firstName: "Ander",     lastName: "Barrenetxea", age: 24, club: "Real Sociedad",   position: "LW",  isRare: false, tmId: 616369,  rating: 78 },
      { id: 127, number: 23, firstName: "Lamine",    lastName: "Yamal",       age: 18, club: "Barcelona",       position: "RW",  isRare: true,  tmId: 937958,  rating: 99 },
      { id: 128, number: 24, firstName: "Yéremy",    lastName: "Pino",        age: 23, club: "Villarreal",      position: "RW",  isRare: false, tmId: 568157,  rating: 82 },
      { id: 129, number: 25, firstName: "Ferran",    lastName: "Torres",      age: 26, club: "Barcelona",       position: "ST",  isRare: false, tmId: 398184,  rating: 82 },
      { id: 130, number: 26, firstName: "Mikel",     lastName: "Oyarzabal",   age: 29, club: "Real Sociedad",   position: "ST",  isRare: true,  tmId: 351478,  rating: 83 },
    ]
  },

  germany: {
    name: "Germany", flag: "🇩🇪", flagCode: "de", color: "#000000", accent: "#dd0000", textColor: "#fff",
    players: [
      { id: 131, number: 1,  firstName: "Manuel",     lastName: "Neuer",         age: 40, club: "Bayern Munich",       position: "GK",  isRare: true,  tmId: 17259,   rating: 69 },
      { id: 132, number: 2,  firstName: "Alexander",  lastName: "Nübel",         age: 29, club: "VfB Stuttgart",       position: "GK",  isRare: false, tmId: 195778,  rating: 78 },
      { id: 133, number: 3,  firstName: "Oliver",     lastName: "Baumann",       age: 35, club: "Hoffenheim",          position: "GK",  isRare: false, tmId: 55089,   rating: 65 },
      { id: 134, number: 4,  firstName: "Antonio",    lastName: "Rüdiger",       age: 33, club: "Real Madrid",         position: "CB",  isRare: true,  tmId: 86202,   rating: 78 },
      { id: 135, number: 5,  firstName: "Nico",       lastName: "Schlotterbeck", age: 26, club: "Borussia Dortmund",   position: "CB",  isRare: false, tmId: 388198,  rating: 84 },
      { id: 136, number: 6,  firstName: "Jonathan",   lastName: "Tah",           age: 30, club: "Bayern Munich",       position: "CB",  isRare: false, tmId: 196357,  rating: 78 },
      { id: 137, number: 7,  firstName: "Waldemar",   lastName: "Anton",         age: 29, club: "Borussia Dortmund",   position: "CB",  isRare: false, tmId: 193004,  rating: 78 },
      { id: 138, number: 8,  firstName: "Malick",     lastName: "Thiaw",         age: 24, club: "Newcastle",           position: "CB",  isRare: false, tmId: 521964,  rating: 82 },
      { id: 139, number: 9,  firstName: "Nathaniel",  lastName: "Brown",         age: 21, club: "Eintracht Frankfurt", position: "RB",  isRare: false, tmId: 691892,  rating: 73 },
      { id: 140, number: 10, firstName: "Joshua",     lastName: "Kimmich",       age: 31, club: "Bayern Munich",       position: "RB",  isRare: true,  tmId: 161056,  rating: 86 },
      { id: 141, number: 11, firstName: "David",      lastName: "Raum",          age: 26, club: "RB Leipzig",          position: "LB",  isRare: false, tmId: 318204,  rating: 80 },
      { id: 142, number: 12, firstName: "Nadiem",     lastName: "Amiri",         age: 29, club: "Mainz",               position: "CAM", isRare: false, tmId: 232454,  rating: 69 },
      { id: 143, number: 13, firstName: "Leon",       lastName: "Goretzka",      age: 31, club: "Bayern Munich",       position: "CM",  isRare: false, tmId: 153084,  rating: 78 },
      { id: 144, number: 14, firstName: "Pascal",     lastName: "Groß",          age: 34, club: "Brighton",            position: "CM",  isRare: false, tmId: 82873,   rating: 73 },
      { id: 145, number: 15, firstName: "Lennart",    lastName: "Karl",          age: 22, club: "Bayern Munich",       position: "CM",  isRare: false, tmId: 1075147, rating: 69 },
      { id: 146, number: 16, firstName: "Jamie",      lastName: "Leweling",      age: 24, club: "VfB Stuttgart",       position: "RW",  isRare: false, tmId: 518505,  rating: 78 },
      { id: 147, number: 17, firstName: "Jamal",      lastName: "Musiala",       age: 23, club: "Bayern Munich",       position: "CAM", isRare: true,  tmId: 580195,  rating: 96 },
      { id: 148, number: 18, firstName: "Felix",      lastName: "Nmecha",        age: 25, club: "Borussia Dortmund",   position: "CM",  isRare: false, tmId: 406640,  rating: 80 },
      { id: 149, number: 19, firstName: "Aleksandar", lastName: "Pavlović",      age: 21, club: "Bayern Munich",       position: "CM",  isRare: false, tmId: 792380,  rating: 84 },
      { id: 150, number: 20, firstName: "Angelo",     lastName: "Stiller",       age: 25, club: "VfB Stuttgart",       position: "CDM", isRare: false, tmId: 443710,  rating: 82 },
      { id: 151, number: 21, firstName: "Maximilian", lastName: "Beier",         age: 23, club: "Borussia Dortmund",   position: "ST",  isRare: false, tmId: 578392,  rating: 82 },
      { id: 152, number: 22, firstName: "Kai",        lastName: "Havertz",       age: 27, club: "Arsenal",             position: "ST",  isRare: true,  tmId: 309400,  rating: 89 },
      { id: 153, number: 23, firstName: "Leroy",      lastName: "Sané",          age: 30, club: "Galatasaray",         position: "RW",  isRare: true,  tmId: 192565,  rating: 80 },
      { id: 154, number: 24, firstName: "Deniz",      lastName: "Undav",         age: 29, club: "VfB Stuttgart",       position: "ST",  isRare: false, tmId: 339314,  rating: 80 },
      { id: 155, number: 25, firstName: "Florian",    lastName: "Wirtz",         age: 23, club: "Liverpool",           position: "CAM", isRare: true,  tmId: 598577,  rating: 96 },
      { id: 156, number: 26, firstName: "Nick",       lastName: "Woltemade",     age: 24, club: "Newcastle",           position: "ST",  isRare: false, tmId: 455661,  rating: 78 },
    ]
  },

  portugal: {
    name: "Portugal", flag: "🇵🇹", flagCode: "pt", color: "#006600", accent: "#ff0000", textColor: "#fff",
    players: [
      { id: 157, number: 1,  firstName: "Diogo",     lastName: "Costa",       age: 26, club: "Porto",           position: "GK",  isRare: false, tmId: 428003,  rating: 86 },
      { id: 158, number: 2,  firstName: "Rui",       lastName: "Silva",       age: 31, club: "Sporting CP",     position: "GK",  isRare: false, tmId: 246464,  rating: 73 },
      { id: 159, number: 3,  firstName: "José",      lastName: "Sá",          age: 33, club: "Wolves",          position: "GK",  isRare: false, tmId: 200488,  rating: 75 },
      { id: 160, number: 4,  firstName: "Rúben",     lastName: "Dias",        age: 29, club: "Man City",        position: "CB",  isRare: true,  tmId: 415471,  rating: 88 },
      { id: 161, number: 5,  firstName: "Gonçalo",   lastName: "Inácio",      age: 24, club: "Sporting CP",     position: "CB",  isRare: false, tmId: 535992,  rating: 84 },
      { id: 162, number: 6,  firstName: "João",      lastName: "Cancelo",     age: 32, club: "Barcelona",       position: "RB",  isRare: true,  tmId: 203460,  rating: 82 },
      { id: 163, number: 7,  firstName: "Nuno",      lastName: "Mendes",      age: 23, club: "PSG",             position: "LB",  isRare: true,  tmId: 549982,  rating: 88 },
      { id: 164, number: 8,  firstName: "Diogo",     lastName: "Dalot",       age: 27, club: "Man United",      position: "RB",  isRare: false, tmId: 392710,  rating: 83 },
      { id: 165, number: 9,  firstName: "Nélson",    lastName: "Semedo",      age: 32, club: "Fenerbahçe",      position: "RB",  isRare: false, tmId: 214086,  rating: 71 },
      { id: 166, number: 10, firstName: "Tomás",     lastName: "Araújo",      age: 23, club: "Benfica",         position: "CB",  isRare: false, tmId: 669217,  rating: 82 },
      { id: 167, number: 11, firstName: "Renato",    lastName: "Veiga",       age: 23, club: "Villarreal",      position: "CB",  isRare: false, tmId: 821478,  rating: 78 },
      { id: 168, number: 12, firstName: "Vitinha",   lastName: "",            age: 26, club: "PSG",             position: "CM",  isRare: true,  tmId: 550645,  rating: 89 },
      { id: 169, number: 13, firstName: "João",      lastName: "Neves",       age: 22, club: "PSG",             position: "CM",  isRare: true,  tmId: 1016878, rating: 93 },
      { id: 170, number: 14, firstName: "Bruno",     lastName: "Fernandes",   age: 31, club: "Man United",      position: "CAM", isRare: true,  tmId: 240306,  rating: 88 },
      { id: 171, number: 15, firstName: "Rúben",     lastName: "Neves",       age: 29, club: "Al-Hilal",        position: "CDM", isRare: false, tmId: 241963,  rating: 75 },
      { id: 172, number: 16, firstName: "Matheus",   lastName: "Nunes",       age: 25, club: "Man City",        position: "CM",  isRare: false, tmId: 626498,  rating: 85 },
      { id: 173, number: 17, firstName: "Samú",      lastName: "Costa",       age: 26, club: "Mallorca",        position: "CM",  isRare: false, tmId: 0,       rating: 73 },
      { id: 174, number: 18, firstName: "Bernardo",  lastName: "Silva",       age: 31, club: "Man City",        position: "CAM", isRare: true,  tmId: 219442,  rating: 89 },
      { id: 175, number: 19, firstName: "Cristiano", lastName: "Ronaldo",     age: 41, club: "Al-Nassr",        position: "ST",  isRare: true,  tmId: 8198,    rating: 75 },
      { id: 176, number: 20, firstName: "Francisco", lastName: "Trincão",     age: 26, club: "Sporting CP",     position: "RW",  isRare: false, tmId: 424913,  rating: 80 },
      { id: 177, number: 21, firstName: "João",      lastName: "Félix",       age: 26, club: "Al-Nassr",        position: "CAM", isRare: true,  tmId: 461468,  rating: 82 },
      { id: 178, number: 22, firstName: "Gonçalo",   lastName: "Ramos",       age: 24, club: "PSG",             position: "ST",  isRare: true,  tmId: 681946,  rating: 88 },
      { id: 179, number: 23, firstName: "Pedro",     lastName: "Neto",        age: 26, club: "Chelsea",         position: "RW",  isRare: true,  tmId: 451384,  rating: 91 },
      { id: 180, number: 24, firstName: "Francisco", lastName: "Conceição",   age: 23, club: "Juventus",        position: "RW",  isRare: false, tmId: 811794,  rating: 85 },
      { id: 181, number: 25, firstName: "Rafael",    lastName: "Leão",        age: 27, club: "AC Milan",        position: "LW",  isRare: true,  tmId: 451376,  rating: 92 },
      { id: 182, number: 26, firstName: "Gonçalo",   lastName: "Guedes",      age: 29, club: "Real Sociedad",   position: "ST",  isRare: false, tmId: 316540,  rating: 71 },
    ]
  },

  netherlands: {
    name: "Netherlands", flag: "🇳🇱", flagCode: "nl", color: "#ff6600", accent: "#003882", textColor: "#fff",
    players: [
      { id: 183, number: 1,  firstName: "Bart",      lastName: "Verbruggen",  age: 23, club: "Brighton",        position: "GK",  isRare: false, tmId: 726304,  rating: 82 },
      { id: 184, number: 2,  firstName: "Mark",      lastName: "Flekken",     age: 32, club: "Brentford",       position: "GK",  isRare: false, tmId: 160644,  rating: 73 },
      { id: 185, number: 3,  firstName: "Robin",     lastName: "Roefs",       age: 27, club: "AZ Alkmaar",      position: "GK",  isRare: false, tmId: 0,       rating: 65 },
      { id: 186, number: 4,  firstName: "Virgil",    lastName: "van Dijk",    age: 34, club: "Liverpool",       position: "CB",  isRare: true,  tmId: 139758,  rating: 78 },
      { id: 187, number: 5,  firstName: "Stefan",    lastName: "de Vrij",     age: 34, club: "Inter Milan",     position: "CB",  isRare: false, tmId: 105694,  rating: 69 },
      { id: 188, number: 6,  firstName: "Nathan",    lastName: "Aké",         age: 31, club: "Man City",        position: "CB",  isRare: false, tmId: 185762,  rating: 80 },
      { id: 189, number: 7,  firstName: "Matthijs",  lastName: "de Ligt",     age: 26, club: "Man United",      position: "CB",  isRare: false, tmId: 326031,  rating: 82 },
      { id: 190, number: 8,  firstName: "Micky",     lastName: "van de Ven",  age: 25, club: "Tottenham",       position: "CB",  isRare: false, tmId: 766289,  rating: 86 },
      { id: 191, number: 9,  firstName: "Jurriën",   lastName: "Timber",      age: 24, club: "Arsenal",         position: "RB",  isRare: true,  tmId: 556956,  rating: 87 },
      { id: 192, number: 10, firstName: "Denzel",    lastName: "Dumfries",    age: 30, club: "Inter Milan",     position: "RB",  isRare: false, tmId: 275167,  rating: 82 },
      { id: 193, number: 11, firstName: "Ian",       lastName: "Maatsen",     age: 23, club: "Aston Villa",     position: "LB",  isRare: false, tmId: 565888,  rating: 82 },
      { id: 194, number: 12, firstName: "Jan Paul",  lastName: "van Hecke",   age: 25, club: "Brighton",        position: "CB",  isRare: false, tmId: 559424,  rating: 80 },
      { id: 195, number: 13, firstName: "Frenkie",   lastName: "de Jong",     age: 29, club: "Barcelona",       position: "CM",  isRare: true,  tmId: 326030,  rating: 88 },
      { id: 196, number: 14, firstName: "Tijjani",   lastName: "Reijnders",   age: 27, club: "AC Milan",        position: "CM",  isRare: true,  tmId: 512229,  rating: 88 },
      { id: 197, number: 15, firstName: "Teun",      lastName: "Koopmeiners", age: 28, club: "Juventus",        position: "CM",  isRare: true,  tmId: 418460,  rating: 87 },
      { id: 198, number: 16, firstName: "Ryan",      lastName: "Gravenberch", age: 24, club: "Liverpool",       position: "CM",  isRare: true,  tmId: 508398,  rating: 89 },
      { id: 199, number: 17, firstName: "Xavi",      lastName: "Simons",      age: 23, club: "RB Leipzig",      position: "CAM", isRare: true,  tmId: 640705,  rating: 92 },
      { id: 200, number: 18, firstName: "Quinten",   lastName: "Timber",      age: 24, club: "Arsenal",         position: "CM",  isRare: false, tmId: 659673,  rating: 82 },
      { id: 201, number: 19, firstName: "Jerdy",     lastName: "Schouten",    age: 29, club: "PSV",             position: "CDM", isRare: false, tmId: 249671,  rating: 78 },
      { id: 202, number: 20, firstName: "Cody",      lastName: "Gakpo",       age: 26, club: "Liverpool",       position: "LW",  isRare: true,  tmId: 546750,  rating: 90 },
      { id: 203, number: 21, firstName: "Donyell",   lastName: "Malen",       age: 27, club: "Dortmund",        position: "RW",  isRare: false, tmId: 369007,  rating: 82 },
      { id: 204, number: 22, firstName: "Steven",    lastName: "Bergwijn",    age: 28, club: "Ajax",            position: "RW",  isRare: false, tmId: 308724,  rating: 75 },
      { id: 205, number: 23, firstName: "Wout",      lastName: "Weghorst",    age: 33, club: "Hoffenheim",      position: "ST",  isRare: false, tmId: 208483,  rating: 69 },
      { id: 206, number: 24, firstName: "Memphis",   lastName: "Depay",       age: 32, club: "Corinthians",     position: "ST",  isRare: true,  tmId: 96910,   rating: 65 },
      { id: 207, number: 25, firstName: "Brian",     lastName: "Brobbey",     age: 24, club: "Ajax",            position: "ST",  isRare: false, tmId: 557008,  rating: 82 },
      { id: 208, number: 26, firstName: "Noa",       lastName: "Lang",        age: 25, club: "PSV",             position: "LW",  isRare: false, tmId: 487153,  rating: 80 },
    ]
  },
};

// Flat list of all players for pack draws
const ALL_PLAYERS = Object.entries(TEAMS).flatMap(([teamId, team]) =>
  team.players.map(p => ({ ...p, teamId, teamName: team.name, teamFlag: team.flag, teamColor: team.color, teamAccent: team.accent }))
);

const TOTAL_STICKERS = ALL_PLAYERS.length; // 208
