#!/bin/bash
# Download missing player photos — updated for current squads
OUT="$(dirname "$0")/images/players"
mkdir -p "$OUT"

UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

fetch() {
  local ID=$1 ARTICLE=$2
  local DEST="$OUT/$ID.jpg"
  [ -f "$DEST" ] && echo "SKIP $ID" && return
  local URL=$(curl -s -A "$UA" "https://en.wikipedia.org/api/rest_v1/page/summary/$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$ARTICLE")" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); t=d.get('thumbnail',{}); url=t.get('source',''); print(url.replace('/280px-','/400px-').replace('/220px-','/400px-').replace('/300px-','/400px-').replace('/150px-','/400px-')) if url else print('')" 2>/dev/null)
  if [ -z "$URL" ]; then echo "NO_URL $ID $ARTICLE"; return; fi
  curl -s -L -A "$UA" -o "$DEST" "$URL"
  local SIZE=$(wc -c < "$DEST" 2>/dev/null || echo 0)
  if [ "$SIZE" -lt 3000 ]; then
    rm -f "$DEST"
    echo "TINY $ID ($SIZE bytes)"
  else
    echo "OK $ID $ARTICLE (${SIZE} bytes)"
  fi
  sleep 0.12
}

echo "=== BRAZIL ==="
fetch 1  "Alisson_Becker"
fetch 2  "Ederson_(footballer,_born_1993)"
fetch 3  "Weverton_(footballer)"
fetch 4  "Marquinhos_(footballer)"
fetch 5  "Gabriel_Magalhães"
fetch 6  "Bremer_(footballer)"
fetch 7  "Roger_Ibañez"
fetch 8  "Léo_Pereira_(footballer,_born_1996)"
fetch 9  "Wesley_(Brazilian_footballer)"
fetch 10 "Danilo_(footballer,_born_1991)"
fetch 11 "Alex_Sandro"
fetch 12 "Douglas_Santos_(footballer)"
fetch 13 "Bruno_Guimarães"
fetch 14 "Casemiro"
fetch 15 "Danilo_Barbosa_(footballer)"
fetch 16 "Fabinho_(footballer,_born_1993)"
fetch 17 "Lucas_Paquetá"
fetch 18 "Raphinha_(footballer)"
fetch 19 "Neymar"
fetch 20 "Vinicius_Junior"
fetch 21 "Luiz_Henrique_(footballer,_born_2001)"
fetch 22 "Matheus_Cunha"
fetch 23 "Gabriel_Martinelli"
fetch 24 "Igor_Thiago"
fetch 25 "Endrick_(footballer)"
fetch 26 "Rayan_(footballer)"

echo "=== ARGENTINA ==="
fetch 27 "Emiliano_Martínez"
fetch 28 "Gerónimo_Rulli"
fetch 29 "Juan_Musso"
fetch 30 "Cristian_Romero"
fetch 31 "Marcos_Senesi"
fetch 32 "Tomás_Palacios_(footballer)"
fetch 33 "Lucas_Martínez_Quarta"
fetch 34 "Nicolás_Otamendi"
fetch 35 "Nicolás_Tagliafico"
fetch 36 "Gabriel_Rojas_(footballer)"
fetch 37 "Marcos_Acuña"
fetch 38 "Nahuel_Molina"
fetch 39 "Agustín_Giay"
fetch 40 "Máximo_Perrone"
fetch 41 "Leandro_Paredes"
fetch 42 "Enzo_Fernández"
fetch 43 "Alexis_Mac_Allister"
fetch 44 "Valentín_Barco"
fetch 45 "Exequiel_Palacios"
fetch 46 "Rodrigo_De_Paul"
fetch 47 "Nico_Paz"
fetch 48 "Nicolás_González_(footballer,_born_1998)"
fetch 49 "Thiago_Almada"
fetch 50 "Franco_Mastantuono"
fetch 51 "Giuliano_Simeone"
fetch 52 "Lionel_Messi"

echo "=== FRANCE ==="
fetch 53 "Mike_Maignan"
fetch 54 "Brice_Samba"
fetch 55 "Robin_Risser"
fetch 56 "William_Saliba"
fetch 57 "Dayot_Upamecano"
fetch 58 "Ibrahima_Konaté_(footballer)"
fetch 59 "Jules_Koundé"
fetch 60 "Malo_Gusto"
fetch 61 "Theo_Hernández"
fetch 62 "Lucas_Hernández_(footballer)"
fetch 63 "Maxence_Lacroix"
fetch 64 "Lucas_Digne"
fetch 65 "Aurélien_Tchouaméni"
fetch 66 "Warren_Zaïre-Emery"
fetch 67 "Adrien_Rabiot"
fetch 68 "N'Golo_Kanté"
fetch 69 "Manu_Koné"
fetch 70 "Kylian_Mbappé"
fetch 71 "Ousmane_Dembélé"
fetch 72 "Marcus_Thuram"
fetch 73 "Bradley_Barcola"
fetch 74 "Michael_Olise"
fetch 75 "Désiré_Doué"
fetch 76 "Rayan_Cherki"
fetch 77 "Maghnes_Akliouche"
fetch 78 "Jean-Philippe_Mateta"

echo "=== ENGLAND ==="
fetch 79  "Jordan_Pickford"
fetch 80  "Dean_Henderson_(footballer)"
fetch 81  "James_Trafford_(goalkeeper)"
fetch 82  "John_Stones"
fetch 83  "Marc_Guéhi"
fetch 84  "Reece_James_(footballer)"
fetch 85  "Ezri_Konsa"
fetch 86  "Jarell_Quansah"
fetch 87  "Dan_Burn"
fetch 88  "Djed_Spence"
fetch 89  "Tino_Livramento"
fetch 90  "Declan_Rice"
fetch 91  "Jude_Bellingham"
fetch 92  "Kobbie_Mainoo"
fetch 93  "Eberechi_Eze"
fetch 94  "Elliot_Anderson_(footballer)"
fetch 95  "Jordan_Henderson_(footballer)"
fetch 96  "Morgan_Rogers_(footballer)"
fetch 97  "Nico_O'Reilly"
fetch 98  "Harry_Kane"
fetch 99  "Bukayo_Saka"
fetch 100 "Marcus_Rashford"
fetch 101 "Ollie_Watkins"
fetch 102 "Anthony_Gordon_(footballer)"
fetch 103 "Ivan_Toney"
fetch 104 "Noni_Madueke"

echo "=== SPAIN ==="
fetch 105 "Joan_García_(goalkeeper)"
fetch 106 "David_Raya"
fetch 107 "Unai_Simón"
fetch 108 "Álex_Remiro"
fetch 109 "Pau_Cubarsí"
fetch 110 "Dean_Huijsen"
fetch 111 "Cristhian_Mosquera"
fetch 112 "Aymeric_Laporte"
fetch 113 "Marc_Cucurella"
fetch 114 "Alejandro_Grimaldo"
fetch 115 "Pedro_Porro"
fetch 116 "Marcos_Llorente"
fetch 117 "Martín_Zubimendi"
fetch 118 "Rodri"
fetch 119 "Pedri"
fetch 120 "Carlos_Soler_(footballer)"
fetch 121 "Pablo_Fornals"
fetch 122 "Fermín_López"
fetch 123 "Dani_Olmo"
fetch 124 "Álex_Baena"
fetch 125 "Víctor_Muñoz_(footballer,_born_2003)"
fetch 126 "Ander_Barrenetxea"
fetch 127 "Lamine_Yamal"
fetch 128 "Yéremy_Pino"
fetch 129 "Ferran_Torres"
fetch 130 "Mikel_Oyarzabal"

echo "=== GERMANY ==="
fetch 131 "Manuel_Neuer"
fetch 132 "Alexander_Nübel"
fetch 133 "Oliver_Baumann_(footballer)"
fetch 134 "Antonio_Rüdiger"
fetch 135 "Nico_Schlotterbeck"
fetch 136 "Jonathan_Tah"
fetch 137 "Waldemar_Anton"
fetch 138 "Malick_Thiaw"
fetch 139 "Nathaniel_Brown_(footballer)"
fetch 140 "Joshua_Kimmich"
fetch 141 "David_Raum"
fetch 142 "Nadiem_Amiri"
fetch 143 "Leon_Goretzka"
fetch 144 "Pascal_Groß"
fetch 145 "Lennart_Karl"
fetch 146 "Jamie_Leweling"
fetch 147 "Jamal_Musiala"
fetch 148 "Felix_Nmecha"
fetch 149 "Aleksandar_Pavlović"
fetch 150 "Angelo_Stiller"
fetch 151 "Maximilian_Beier"
fetch 152 "Kai_Havertz"
fetch 153 "Leroy_Sané"
fetch 154 "Deniz_Undav"
fetch 155 "Florian_Wirtz"
fetch 156 "Nick_Woltemade"

echo "=== PORTUGAL ==="
fetch 157 "Diogo_Costa_(footballer,_born_1999)"
fetch 158 "Rui_Silva_(footballer,_born_1994)"
fetch 159 "José_Sá"
fetch 160 "Rúben_Dias"
fetch 161 "Gonçalo_Inácio"
fetch 162 "João_Cancelo"
fetch 163 "Nuno_Mendes_(footballer,_born_2002)"
fetch 164 "Diogo_Dalot"
fetch 165 "Nélson_Semedo"
fetch 166 "Tomás_Araújo_(footballer)"
fetch 167 "Renato_Veiga_(footballer)"
fetch 168 "Vitinha_(footballer)"
fetch 169 "João_Neves_(footballer)"
fetch 170 "Bruno_Fernandes_(midfielder)"
fetch 171 "Rúben_Neves"
fetch 172 "Matheus_Nunes_(footballer)"
fetch 173 "Samú_Costa_(footballer)"
fetch 174 "Bernardo_Silva"
fetch 175 "Cristiano_Ronaldo"
fetch 176 "Francisco_Trincão"
fetch 177 "João_Félix"
fetch 178 "Gonçalo_Ramos"
fetch 179 "Pedro_Neto_(footballer)"
fetch 180 "Francisco_Conceição_(footballer)"
fetch 181 "Rafael_Leão"
fetch 182 "Gonçalo_Guedes"

echo "=== NETHERLANDS ==="
fetch 183 "Bart_Verbruggen"
fetch 184 "Mark_Flekken"
fetch 185 "Robin_Roefs"
fetch 186 "Virgil_van_Dijk"
fetch 187 "Stefan_de_Vrij"
fetch 188 "Nathan_Aké"
fetch 189 "Matthijs_de_Ligt"
fetch 190 "Micky_van_de_Ven"
fetch 191 "Jurriën_Timber"
fetch 192 "Denzel_Dumfries"
fetch 193 "Ian_Maatsen"
fetch 194 "Jan_Paul_van_Hecke"
fetch 195 "Frenkie_de_Jong"
fetch 196 "Tijjani_Reijnders"
fetch 197 "Teun_Koopmeiners"
fetch 198 "Ryan_Gravenberch"
fetch 199 "Xavi_Simons"
fetch 200 "Quinten_Timber"
fetch 201 "Jerdy_Schouten"
fetch 202 "Cody_Gakpo"
fetch 203 "Donyell_Malen"
fetch 204 "Steven_Bergwijn"
fetch 205 "Wout_Weghorst"
fetch 206 "Memphis_Depay"
fetch 207 "Brian_Brobbey"
fetch 208 "Noa_Lang_(footballer)"

echo ""
echo "Total photos: $(ls "$OUT"/*.jpg 2>/dev/null | wc -l)"
