#!/bin/bash
# Download ALL 208 player photos from Wikipedia REST API
OUT="$(dirname "$0")/images/players"
mkdir -p "$OUT"

UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

fetch() {
  local ID=$1 ARTICLE=$2
  local DEST="$OUT/$ID.jpg"
  [ -f "$DEST" ] && echo "SKIP $ID" && return
  local URL=$(curl -s -A "$UA" "https://en.wikipedia.org/api/rest_v1/page/summary/$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$ARTICLE")" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); t=d.get('thumbnail',{}); url=t.get('source',''); print(url.replace('/280px-','/400px-').replace('/220px-','/400px-').replace('/300px-','/400px-').replace('/150px-','/400px-')) if url else print('')" 2>/dev/null)
  if [ -z "$URL" ]; then echo "NO_URL $ID $ARTICLE"; return; fi
  curl -s -L -A "$UA" -o "$DEST" "$URL"
  local SIZE=$(wc -c < "$DEST" 2>/dev/null || echo 0)
  if [ "$SIZE" -lt 3000 ]; then
    rm -f "$DEST"
    echo "TINY $ID ($SIZE bytes)"
  else
    echo "OK $ID $ARTICLE (${SIZE} bytes)"
  fi
  sleep 0.15
}

echo "=== BRAZIL (1-26) ==="
fetch 1  "Alisson_Becker"
fetch 2  "Ederson_(footballer,_born_1993)"
fetch 3  "Weverton"
fetch 4  "Gabriel_Magalhães"
fetch 5  "Bremer_(footballer)"
fetch 6  "Marquinhos_(footballer,_born_1994)"
fetch 7  "Roger_Ibañez"
fetch 8  "Léo_Pereira_(footballer,_born_1996)"
fetch 9  "Danilo_(footballer,_born_1991)"
fetch 10 "Wesley_(Brazilian_footballer)"
fetch 11 "Douglas_Santos_(footballer)"
fetch 12 "Alex_Sandro"
fetch 13 "Bruno_Guimarães"
fetch 14 "Casemiro"
fetch 15 "Danilo_Barbosa_(footballer)"
fetch 16 "Fabinho_(footballer,_born_1993)"
fetch 17 "Lucas_Paquetá"
fetch 18 "Neymar"
fetch 19 "Vinícius_Júnior"
fetch 20 "Raphinha"
fetch 21 "Gabriel_Martinelli"
fetch 22 "Rayan_(footballer)"
fetch 23 "Luiz_Henrique_(footballer,_born_2001)"
fetch 24 "Matheus_Cunha"
fetch 25 "Igor_Thiago"
fetch 26 "Endrick"

echo "=== ARGENTINA (27-52) ==="
fetch 27 "Emiliano_Martínez"
fetch 28 "Gerónimo_Rulli"
fetch 29 "Juan_Musso"
fetch 30 "Cristian_Romero"
fetch 31 "Marcos_Senesi"
fetch 32 "Tomás_Palacios_(footballer)"
fetch 33 "Nahuel_Molina"
fetch 34 "Agustín_Giay"
fetch 35 "Nicolás_Tagliafico"
fetch 36 "Gabriel_Rojas_(footballer,_born_1998)"
fetch 37 "Máximo_Perrone"
fetch 38 "Leandro_Paredes"
fetch 39 "Enzo_Fernández"
fetch 40 "Alexis_Mac_Allister"
fetch 41 "Valentín_Barco"
fetch 42 "Exequiel_Palacios"
fetch 43 "Rodrigo_De_Paul"
fetch 44 "Nicolás_Paz_(footballer)"
fetch 45 "Thiago_Almada"
fetch 46 "Nicolás_González_(footballer,_born_1998)"
fetch 47 "Franco_Mastantuono"
fetch 48 "Giuliano_Simeone"
fetch 49 "Lionel_Messi"
fetch 50 "Gianluca_Prestianni"
fetch 51 "Julián_Álvarez"
fetch 52 "José_Manuel_López_(footballer,_born_2001)"

echo "=== FRANCE (53-78) ==="
fetch 53 "Mike_Maignan"
fetch 54 "Robin_Risser"
fetch 55 "Brice_Samba"
fetch 56 "William_Saliba"
fetch 57 "Dayot_Upamecano"
fetch 58 "Ibrahima_Konaté_(footballer)"
fetch 59 "Maxence_Lacroix"
fetch 60 "Jules_Koundé"
fetch 61 "Malo_Gusto"
fetch 62 "Theo_Hernández"
fetch 63 "Lucas_Hernández_(footballer)"
fetch 64 "Lucas_Digne"
fetch 65 "Aurélien_Tchouaméni"
fetch 66 "N'Golo_Kanté"
fetch 67 "Warren_Zaïre-Emery"
fetch 68 "Manu_Koné"
fetch 69 "Adrien_Rabiot"
fetch 70 "Rayan_Cherki"
fetch 71 "Bradley_Barcola"
fetch 72 "Michael_Olise"
fetch 73 "Désiré_Doué"
fetch 74 "Maghnes_Akliouche"
fetch 75 "Kylian_Mbappé"
fetch 76 "Ousmane_Dembélé"
fetch 77 "Marcus_Thuram"
fetch 78 "Jean-Philippe_Mateta"

echo "=== ENGLAND (79-104) ==="
fetch 79 "Dean_Henderson_(footballer)"
fetch 80 "James_Trafford_(goalkeeper)"
fetch 81 "Jordan_Pickford"
fetch 82 "Marc_Guéhi"
fetch 83 "Jarell_Quansah"
fetch 84 "Ezri_Konsa"
fetch 85 "John_Stones"
fetch 86 "Dan_Burn"
fetch 87 "Reece_James_(footballer)"
fetch 88 "Tino_Livramento"
fetch 89 "Nico_O'Reilly"
fetch 90 "Djed_Spence"
fetch 91 "Declan_Rice"
fetch 92 "Kobbie_Mainoo"
fetch 93 "Jordan_Henderson"
fetch 94 "Elliot_Anderson_(footballer)"
fetch 95 "Jude_Bellingham"
fetch 96 "Morgan_Rogers_(footballer)"
fetch 97 "Eberechi_Eze"
fetch 98 "Anthony_Gordon_(footballer)"
fetch 99 "Marcus_Rashford"
fetch 100 "Bukayo_Saka"
fetch 101 "Noni_Madueke"
fetch 102 "Harry_Kane"
fetch 103 "Ollie_Watkins"
fetch 104 "Ivan_Toney"

echo "=== SPAIN (105-130) ==="
fetch 105 "Joan_García_(footballer,_born_2001)"
fetch 106 "David_Raya"
fetch 107 "Unai_Simón"
fetch 108 "Pau_Cubarsí"
fetch 109 "Dean_Huijsen"
fetch 110 "Cristhian_Mosquera"
fetch 111 "Aymeric_Laporte"
fetch 112 "Pedro_Porro"
fetch 113 "Marcos_Llorente"
fetch 114 "Marc_Cucurella"
fetch 115 "Álex_Grimaldo"
fetch 116 "Martín_Zubimendi"
fetch 117 "Rodri_(footballer,_born_1996)"
fetch 118 "Pedri"
fetch 119 "Carlos_Soler"
fetch 120 "Pablo_Fornals"
fetch 121 "Fermín_López"
fetch 122 "Dani_Olmo"
fetch 123 "Álex_Baena"
fetch 124 "Víctor_Muñoz_(footballer,_born_2004)"
fetch 125 "Ander_Barrenetxea"
fetch 126 "Lamine_Yamal"
fetch 127 "Yéremy_Pino"
fetch 128 "Ferran_Torres"
fetch 129 "Mikel_Oyarzabal"
fetch 130 "Borja_Iglesias"

echo "=== GERMANY (131-156) ==="
fetch 131 "Alexander_Nübel"
fetch 132 "Manuel_Neuer"
fetch 133 "Oliver_Baumann_(footballer)"
fetch 134 "Nico_Schlotterbeck"
fetch 135 "Malick_Thiaw"
fetch 136 "Jonathan_Tah"
fetch 137 "Waldemar_Anton"
fetch 138 "Antonio_Rüdiger"
fetch 139 "Nathaniel_Brown_(footballer)"
fetch 140 "David_Raum"
fetch 141 "Joshua_Kimmich"
fetch 142 "Aleksandar_Pavlović_(footballer)"
fetch 143 "Angelo_Stiller"
fetch 144 "Felix_Nmecha"
fetch 145 "Nadiem_Amiri"
fetch 146 "Leon_Goretzka"
fetch 147 "Pascal_Groß"
fetch 148 "Jamal_Musiala"
fetch 149 "Florian_Wirtz"
fetch 150 "Lennart_Karl"
fetch 151 "Jamie_Leweling"
fetch 152 "Leroy_Sané"
fetch 153 "Nick_Woltemade"
fetch 154 "Kai_Havertz"
fetch 155 "Maximilian_Beier"
fetch 156 "Deniz_Undav"

echo "=== PORTUGAL (157-182) ==="
fetch 157 "Diogo_Costa_(goalkeeper)"
fetch 158 "Rui_Silva_(footballer,_born_1994)"
fetch 159 "José_Sá"
fetch 160 "Rúben_Dias"
fetch 161 "Gonçalo_Inácio"
fetch 162 "Tomás_Araújo_(footballer)"
fetch 163 "Renato_Veiga_(footballer)"
fetch 164 "Nuno_Mendes_(footballer,_born_2002)"
fetch 165 "Diogo_Dalot"
fetch 166 "Matheus_Nunes_(footballer)"
fetch 167 "João_Cancelo"
fetch 168 "Nélson_Semedo"
fetch 169 "Vitinha_(footballer,_born_2000)"
fetch 170 "Rúben_Neves"
fetch 171 "Samú_Costa_(footballer)"
fetch 172 "João_Neves_(footballer)"
fetch 173 "Bruno_Fernandes_(footballer,_born_1994)"
fetch 174 "Francisco_Trincão"
fetch 175 "Bernardo_Silva"
fetch 176 "Rafael_Leão"
fetch 177 "Gonçalo_Guedes"
fetch 178 "Pedro_Neto_(footballer,_born_1999)"
fetch 179 "Francisco_Conceição_(footballer)"
fetch 180 "João_Félix"
fetch 181 "Gonçalo_Ramos"
fetch 182 "Cristiano_Ronaldo"

echo "=== NETHERLANDS (183-208) ==="
fetch 183 "Bart_Verbruggen"
fetch 184 "Mark_Flekken"
fetch 185 "Justin_Bijlow"
fetch 186 "Micky_van_de_Ven"
fetch 187 "Jan_Paul_van_Hecke"
fetch 188 "Virgil_van_Dijk"
fetch 189 "Nathan_Aké"
fetch 190 "Stefan_de_Vrij"
fetch 191 "Jorrel_Hato"
fetch 192 "Jeremie_Frimpong"
fetch 193 "Denzel_Dumfries"
fetch 194 "Lutsharel_Geertruida"
fetch 195 "Ryan_Gravenberch"
fetch 196 "Jerdy_Schouten"
fetch 197 "Teun_Koopmeiners"
fetch 198 "Tijjani_Reijnders"
fetch 199 "Kees_Smit_(footballer)"
fetch 200 "Quinten_Timber"
fetch 201 "Luciano_Valente_(footballer)"
fetch 202 "Xavi_Simons"
fetch 203 "Cody_Gakpo"
fetch 204 "Noa_Lang_(footballer)"
fetch 205 "Donyell_Malen"
fetch 206 "Brian_Brobbey"
fetch 207 "Wout_Weghorst"
fetch 208 "Memphis_Depay"

echo ""
echo "Total photos: $(ls "$OUT"/*.jpg 2>/dev/null | wc -l) / 208"
