#!/bin/bash
# Download missing player photos after the 208-sticker remap
OUT="$(dirname "$0")/images/players"
mkdir -p "$OUT"

UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

fetch() {
  local ID=$1 ARTICLE=$2
  local DEST="$OUT/$ID.jpg"
  [ -f "$DEST" ] && echo "SKIP $ID" && return
  local URL=$(curl -s -A "$UA" "https://en.wikipedia.org/api/rest_v1/page/summary/$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$ARTICLE")" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); t=d.get('thumbnail',{}); url=t.get('source',''); print(url.replace('/280px-','/400px-').replace('/220px-','/400px-').replace('/300px-','/400px-').replace('/150px-','/400px-')) if url else print('')" 2>/dev/null)
  if [ -z "$URL" ]; then echo "NO_URL $ID $ARTICLE"; return; fi
  curl -s -L -A "$UA" -o "$DEST" "$URL"
  local SIZE=$(wc -c < "$DEST" 2>/dev/null || echo 0)
  if [ "$SIZE" -lt 3000 ]; then
    rm -f "$DEST"
    echo "TINY $ID ($SIZE bytes)"
  else
    echo "OK $ID $ARTICLE (${SIZE} bytes)"
  fi
  sleep 0.12
}

echo "=== BRAZIL ==="
fetch 5  "Gabriel_Magalhães"
fetch 6  "Bremer_(footballer)"
fetch 7  "Arthur_(footballer,_born_1999)"
fetch 8  "Léo_Pereira_(footballer,_born_1996)"
fetch 9  "Wesley_(Brazilian_footballer)"
fetch 10 "Danilo_(footballer,_born_1991)"
fetch 11 "Alex_Sandro"
fetch 12 "Douglas_Santos_(footballer)"
fetch 13 "Bruno_Guimarães"
fetch 15 "Danilo_Barbosa_(footballer)"
fetch 16 "Fabinho_(footballer,_born_1993)"
fetch 17 "Lucas_Paquetá"
fetch 18 "Raphinha_(footballer)"
fetch 19 "Neymar"
fetch 21 "Luiz_Henrique_(footballer,_born_2001)"
fetch 22 "Matheus_Cunha"
fetch 24 "Igor_Thiago"
fetch 26 "Rayan_(footballer)"

echo "=== ARGENTINA ==="
fetch 28 "Gerónimo_Rulli"
fetch 30 "Cristian_Romero"
fetch 33 "Germán_Pezzella"
fetch 37 "Facundo_Medina_(footballer)"
fetch 40 "Alexis_Mac_Allister"
fetch 42 "Exequiel_Palacios"
fetch 43 "Giovani_Lo_Celso"
fetch 44 "Thiago_Almada"
fetch 50 "Nicolás_González_(footballer,_born_1998)"
fetch 51 "Giuliano_Simeone"
fetch 52 "Claudio_Echeverri"

echo "=== FRANCE ==="
fetch 55 "Robin_Risser"
fetch 58 "Ibrahima_Konaté_(footballer)"
fetch 59 "Jules_Koundé"
fetch 60 "Malo_Gusto"
fetch 61 "Theo_Hernández"
fetch 62 "Lucas_Hernández_(footballer)"
fetch 63 "Maxence_Lacroix"
fetch 64 "Lucas_Digne"
fetch 65 "Aurélien_Tchouaméni"
fetch 68 "N'Golo_Kanté"
fetch 69 "Manu_Koné"
fetch 70 "Kylian_Mbappé"
fetch 72 "Marcus_Thuram"
fetch 73 "Bradley_Barcola"
fetch 74 "Michael_Olise"
fetch 75 "Désiré_Doué"
fetch 76 "Rayan_Cherki"
fetch 77 "Maghnes_Akliouche"
fetch 78 "Jean-Philippe_Mateta"

echo "=== ENGLAND ==="
fetch 80 "Dean_Henderson_(footballer)"
fetch 81 "James_Trafford_(goalkeeper)"
fetch 84 "Reece_James_(footballer)"
fetch 85 "Ezri_Konsa"
fetch 86 "Jarell_Quansah"
fetch 87 "Dan_Burn"
fetch 88 "Djed_Spence"
fetch 89 "Tino_Livramento"
fetch 90 "Declan_Rice"
fetch 91 "Jude_Bellingham"
fetch 93 "Eberechi_Eze"
fetch 94 "Elliot_Anderson_(footballer)"
fetch 95 "Jordan_Henderson_(footballer)"
fetch 96 "Morgan_Rogers_(footballer)"
fetch 97 "Nico_O'Reilly"
fetch 98 "Harry_Kane"
fetch 102 "Anthony_Gordon_(footballer)"
fetch 103 "Ivan_Toney"
fetch 104 "Noni_Madueke"

echo "=== SPAIN ==="
fetch 105 "Unai_Simón"
fetch 108 "Pau_Cubarsí"
fetch 109 "Robin_Le_Normand"
fetch 110 "Aymeric_Laporte"
fetch 111 "Alejandro_Balde"
fetch 112 "Pedro_Porro"
fetch 113 "Marc_Cucurella"
fetch 114 "Dani_Vivian_(footballer)"
fetch 115 "Álex_Grimaldo"
fetch 121 "Dani_Olmo"
fetch 122 "Álex_Baena"
fetch 123 "Fermín_López"
fetch 124 "Lamine_Yamal"
fetch 125 "Nico_Williams_(footballer)"
fetch 127 "Ferran_Torres"
fetch 129 "Samuel_Aghehowa"

echo "=== GERMANY ==="
fetch 132 "Alexander_Nübel"
fetch 133 "Oliver_Baumann_(footballer)"
fetch 134 "Antonio_Rüdiger"
fetch 135 "Nico_Schlotterbeck"
fetch 137 "Waldemar_Anton"
fetch 138 "Malick_Thiaw"
fetch 139 "Nathaniel_Brown_(footballer)"
fetch 142 "Nadiem_Amiri"
fetch 143 "Leon_Goretzka"
fetch 144 "Pascal_Groß"
fetch 145 "Lennart_Karl"
fetch 146 "Jamie_Leweling"
fetch 147 "Jamal_Musiala"
fetch 148 "Felix_Nmecha"
fetch 150 "Angelo_Stiller"
fetch 151 "Maximilian_Beier"
fetch 152 "Kai_Havertz"
fetch 154 "Deniz_Undav"
fetch 156 "Nick_Woltemade"

echo "=== PORTUGAL ==="
fetch 158 "Rui_Silva_(footballer,_born_1994)"
fetch 160 "Rúben_Dias"
fetch 161 "Gonçalo_Inácio"
fetch 162 "João_Cancelo"
fetch 164 "Diogo_Dalot"
fetch 166 "Tomás_Araújo_(footballer)"
fetch 167 "Renato_Veiga_(footballer)"
fetch 168 "Vitinha_(footballer)"
fetch 169 "João_Neves_(footballer)"
fetch 170 "Bruno_Fernandes_(midfielder)"
fetch 171 "Rúben_Neves"
fetch 172 "Matheus_Nunes_(footballer)"
fetch 173 "Samú_Costa_(footballer)"
fetch 174 "Bernardo_Silva"
fetch 175 "Cristiano_Ronaldo"
fetch 176 "Francisco_Trincão"
fetch 178 "Gonçalo_Ramos"
fetch 179 "Pedro_Neto"
fetch 182 "Gonçalo_Guedes"

echo "=== NETHERLANDS ==="
fetch 185 "Robin_Roefs"
fetch 187 "Stefan_de_Vrij"
fetch 190 "Micky_van_de_Ven"
fetch 194 "Jan_Paul_van_Hecke"
fetch 196 "Tijjani_Reijnders"
fetch 198 "Ryan_Gravenberch"
fetch 201 "Jerdy_Schouten"
fetch 205 "Wout_Weghorst"
fetch 208 "Noa_Lang_(footballer)"

echo ""
echo "Total photos: $(ls "$OUT"/*.jpg | wc -l)"
