#!/bin/bash
# Download player photos from Wikipedia using curl (follows redirects)
OUT="$(dirname "$0")/images/players"
mkdir -p "$OUT"

UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

fetch() {
  local ID=$1 ARTICLE=$2
  local DEST="$OUT/$ID.jpg"
  [ -f "$DEST" ] && echo "SKIP $ID" && return
  # Get thumbnail URL from Wikipedia summary API
  local URL=$(curl -s -A "$UA" "https://en.wikipedia.org/api/rest_v1/page/summary/$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$ARTICLE")" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); t=d.get('thumbnail',{}); url=t.get('source',''); print(url.replace('/280px-','/400px-').replace('/220px-','/400px-').replace('/300px-','/400px-')) if url else print('')" 2>/dev/null)
  if [ -z "$URL" ]; then echo "NO_URL $ID $ARTICLE"; return; fi
  curl -s -L -A "$UA" -o "$DEST" "$URL"
  local SIZE=$(wc -c < "$DEST" 2>/dev/null || echo 0)
  if [ "$SIZE" -lt 3000 ]; then
    rm -f "$DEST"
    echo "TINY $ID ($SIZE bytes)"
  else
    echo "OK $ID $ARTICLE (${SIZE} bytes)"
  fi
  sleep 0.15
}

# All players needing photos (run fetch for each)
fetch 31 "Nicolas_Tagliafico"
fetch 32 "Lionel_Messi"
fetch 33 "Angel_Di_Maria"
fetch 34 "Rodrigo_De_Paul"
fetch 35 "Leandro_Paredes"
fetch 36 "Enzo_Fernández"
fetch 37 "Exequiel_Palacios"
fetch 38 "Lautaro_Martínez"
fetch 39 "Julián_Álvarez"
fetch 40 "Paulo_Dybala"
fetch 41 "Alejandro_Garnacho"
fetch 42 "Thiago_Almada"
fetch 43 "Giovani_Lo_Celso"
fetch 44 "Valentín_Carboni"
fetch 45 "Mike_Maignan"
fetch 46 "Alphonse_Aréola"
fetch 47 "Brice_Samba"
fetch 48 "William_Saliba"
fetch 49 "Dayot_Upamecano"
fetch 50 "Ibrahima_Konaté_(footballer)"
fetch 51 "Jules_Koundé"
fetch 52 "Benjamin_Pavard"
fetch 53 "Theo_Hernández"
fetch 54 "Lucas_Hernández_(footballer)"
fetch 55 "Aurélien_Tchouaméni"
fetch 56 "Adrien_Rabiot"
fetch 57 "Eduardo_Camavinga"
fetch 58 "Antoine_Griezmann"
fetch 59 "Warren_Zaïre-Emery"
fetch 60 "Kylian_Mbappé"
fetch 61 "Ousmane_Dembélé"
fetch 62 "Marcus_Thuram"
fetch 63 "Kingsley_Coman"
fetch 64 "Bradley_Barcola"
fetch 65 "Randal_Kolo_Muani"
fetch 66 "Matteo_Guendouzi"
fetch 67 "Jordan_Pickford"
fetch 68 "Aaron_Ramsdale"
fetch 69 "Nick_Pope_(footballer)"
fetch 70 "John_Stones"
fetch 71 "Harry_Maguire"
fetch 72 "Marc_Guéhi"
fetch 73 "Trent_Alexander-Arnold"
fetch 74 "Reece_James_(footballer)"
fetch 75 "Luke_Shaw"
fetch 76 "Declan_Rice"
fetch 77 "Jude_Bellingham"
fetch 78 "Phil_Foden"
fetch 79 "Kobbie_Mainoo"
fetch 80 "Conor_Gallagher_(footballer)"
fetch 81 "Harry_Kane"
fetch 82 "Bukayo_Saka"
fetch 83 "Marcus_Rashford"
fetch 84 "Ollie_Watkins"
fetch 85 "Jarrod_Bowen"
fetch 86 "Cole_Palmer_(footballer)"
fetch 87 "Anthony_Gordon_(footballer)"
fetch 88 "Levi_Colwill"
fetch 89 "Unai_Simón"
fetch 90 "David_Raya"
fetch 91 "Robert_Sánchez_(footballer,_born_1997)"
fetch 92 "Aymeric_Laporte"
fetch 93 "Robin_Le_Normand"
fetch 94 "Pau_Cubarsí"
fetch 95 "Dani_Carvajal"
fetch 96 "Pedro_Porro"
fetch 97 "Alejandro_Balde"
fetch 98 "Rodri_(footballer)"
fetch 99 "Pedri"
fetch 100 "Gavi_(footballer)"
fetch 101 "Fabián_Ruiz"
fetch 102 "Martín_Zubimendi"
fetch 103 "Lamine_Yamal"
fetch 104 "Nico_Williams"
fetch 105 "Álvaro_Morata"
fetch 106 "Mikel_Oyarzabal"
fetch 107 "Ferran_Torres"
fetch 108 "Dani_Olmo"
fetch 109 "Joselu"
fetch 110 "Bryan_Gil"
fetch 111 "Manuel_Neuer"
fetch 112 "Marc-André_ter_Stegen"
fetch 113 "Oliver_Baumann"
fetch 114 "Antonio_Rüdiger"
fetch 115 "Nico_Schlotterbeck"
fetch 116 "Jonathan_Tah"
fetch 117 "Joshua_Kimmich"
fetch 118 "David_Raum_(footballer)"
fetch 119 "Maximilian_Mittelstädt"
fetch 120 "İlkay_Gündoğan"
fetch 121 "Florian_Wirtz"
fetch 122 "Jamal_Musiala"
fetch 123 "Leon_Goretzka"
fetch 124 "Leroy_Sané"
fetch 125 "Thomas_Müller"
fetch 126 "Kai_Havertz"
fetch 127 "Serge_Gnabry"
fetch 128 "Niclas_Füllkrug"
fetch 129 "Deniz_Undav"
fetch 130 "Angelo_Stiller"
fetch 131 "Aleksandar_Pavlović_(footballer)"
fetch 132 "Karim_Adeyemi"
fetch 133 "Diogo_Costa_(goalkeeper)"
fetch 134 "Rui_Patrício"
fetch 135 "José_Sá"
fetch 136 "Rúben_Dias"
fetch 137 "Pepe_(footballer)"
fetch 138 "António_Silva_(footballer,_born_2003)"
fetch 139 "João_Cancelo"
fetch 140 "Nuno_Mendes_(footballer,_born_2002)"
fetch 141 "Cristiano_Ronaldo"
fetch 142 "Bernardo_Silva"
fetch 143 "Bruno_Fernandes_(midfielder)"
fetch 144 "Vitinha_(footballer)"
fetch 145 "João_Palhinha"
fetch 146 "Rúben_Neves"
fetch 147 "Diogo_Jota"
fetch 148 "Rafael_Leão"
fetch 149 "Pedro_Neto"
fetch 150 "Gonçalo_Ramos"
fetch 151 "João_Félix"
fetch 152 "Francisco_Conceição_(footballer)"
fetch 153 "Mateus_Fernandes_(footballer)"
fetch 154 "Nelson_Semedo"
fetch 155 "Bart_Verbruggen"
fetch 156 "Mark_Flekken"
fetch 157 "Nick_Olij"
fetch 158 "Virgil_van_Dijk"
fetch 159 "Stefan_de_Vrij"
fetch 160 "Nathan_Aké"
fetch 161 "Denzel_Dumfries"
fetch 162 "Jurriën_Timber"
fetch 163 "Matthijs_de_Ligt"
fetch 164 "Frenkie_de_Jong"
fetch 165 "Tijjani_Reijnders"
fetch 166 "Teun_Koopmeiners"
fetch 167 "Xavi_Simons"
fetch 168 "Ryan_Gravenberch"
fetch 169 "Cody_Gakpo"
fetch 170 "Donyell_Malen"
fetch 171 "Steven_Bergwijn"
fetch 172 "Wout_Weghorst"
fetch 173 "Memphis_Depay"
fetch 174 "Brian_Brobbey"
fetch 175 "Quinten_Timber"
fetch 176 "Ian_Maatsen"

echo ""
echo "Total photos: $(ls "$OUT" | wc -l)"
